### ISSUE TITLE
Errors not being captured by handleError subscription

### ISSUE THREAD

**Issue by rjdlee** [parse-community/ParseLiveQuery-iOS-OSX#102]
I want to capture and handle errors such as:

`Error: Optional(Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 502" UserInfo={NSLocalizedDescription=received bad response code from server 502, HTTPResponseStatusCode=502})`

However, my code doesn't work. errorSubscription is saved as a property of the view controller.

`errorSubscription = liveQueryClient.subscribe(liveQuery).handleError({ (_, error) in
                    print("Live query error \(error.localizedDescription)") // Never runs
                })`

My Event.created handler works correctly:

`createdSubscription = liveQueryClient.subscribe(liveQuery).handle(Event.created, { (query, object) in
                     // Runs correctly
                })`

**Comment by flovilmart** [comment]
Try updating to version 2.0.0

**Comment by rjdlee** [comment]
Nope, still doesn't seem to work. The error I mentioned previously is being outputted in a different format though. For context on the error, I'm generating it when I stop my Parse server.

`error: Optional(Error Domain=WebSocket Code=502 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade})`

**Comment by flovilmart** [comment]
I'll have a look

**Comment by flovilmart** [comment]
@rjdlee I had a look to the code, and the error handler bound is to the websocket connection errors but to the server forwarded errors. We could very well bind those, but the LiveQuery Client is supposedly reconnecting automatically (without exponential backoff nor limit)

**Comment by rjdlee** [comment]
It could be useful to bind them for detecting when the app is offline. Not necessary by any means though. Thanks for the help.
