### ISSUE TITLE
I cant seem to get any responses from the live query server

### ISSUE THREAD

**Issue by Charlesleonius** [parse-community/ParseLiveQuery-iOS-OSX#104]
I do get the "Subbed" message but I can't seem to get any events when objects are added to the class or anything else for that matter. Is there some way I can verify that my live query server is working or see some error messages?

```let liveQueryClient = ParseLiveQuery.Client()
    var subscription: Subscription<Message>?
    var room = "room"
    
    override func viewDidLoad() {
        self.senderDisplayName = PFUser.current()?.username
        self.senderId = PFUser.current()?.objectId
        register()
        super.viewDidLoad()
    }
    
    func register() {
        let messageQuery: PFQuery<Message>  = Message.query()!.whereKey("room", equalTo: "room") as! PFQuery<Message>
        subscription = liveQueryClient.subscribe(messageQuery).handleSubscribe { [weak self]  (_) in
                print("Subbed")
            }.handleEvent { [weak self] (_, event) in
                self?.handleEvent(event: event)
        }
    }
    
    func handleEvent(event: Event<Message>) {
        // Make sure we're on main thread
        if Thread.current != Thread.main {
            return DispatchQueue.main.async { [weak self] _ in
                self?.handleEvent(event: event)
            }
        }
        
        switch event {
        case .created(let obj),
             .entered(let obj):
            print("Object is entered!")
            
        case .updated(let obj):
            print("Object is updated!")
            
        case .deleted(let obj),
             .left(let obj):
            print("Object is deleted!")
        }
    }```

**Comment by flovilmart** [comment]
You can verify it in the Xcode logs, if the liveQueryClient can't connect, there will be logs in the console.

On the server, when running with VERBOSE=1 you should see logs of incoming new clients.

**Comment by Charlesleonius** [comment]
I can see when a client connects to the server now but Is there anyway to see  logs or errors on the client side? I see the subscriptions on my Heroku logs but I'm still not getting any events in my ios application. I'm used to the completion handler style of the Parse library so the ParseLiveQuery library is giving me a lot of trouble.

**Comment by rickrl1** [comment]
Any progress on this? I have the same problem where I seem to subscribe correctly but I'm not receiving any events. This is really halting my progress at the moment so very keen for any advice.

**Comment by Charlesleonius** [comment]
Turned out to be related to the Class Level Permissions. Even though the subscriber was the one with access it still wouldn't receive any events until I made the read access public

**Comment by rickrl1** [comment]
Thanks so much!! That was the issue - as soon as I added public read permissions, the events stated coming through.

________________________________

**Comment by Charlesleonius** [comment]
No problem, be wary of class level permissions when dealing with live queries though. As far as I can tell not all ACL's are effective on live queries at the moment so if you are using them for sensitive data be sure to test the ACL's thoroughly.

**Comment by peuf0u** [comment]
Hi guys, I have exactly the same issue as you had, I am getting the "Subed" but I can't get any events. My parse is running on heroku and my ACL's are set to public. I am really desperate on this. Do you please have any suggestions what could be wrong? Any advice would really helped, thanks.

**Comment by flovilmart** [comment]
Closing as resolved. Please open a new issue with your code
