### ISSUE TITLE
CreateHandler doesn't always fire when running multiple dynos on Heroku.

### ISSUE THREAD

**Issue by camdengaba** [parse-community/ParseLiveQuery-iOS-OSX#107]
I apologize in advance if this is not the right place to ask for help.

I'm running ParseServer on Heroku and I'm using ParseLiveQuery to power a real-time chat view.  I'm using multiple dynos on Heroku.  The problem is that the createHandler for my subscription is only firing sometimes.  It seems that the LiveQuery client is only running on a single dyno and doesn't notice object creations that occur on another dyno.

**Comment by flovilmart** [comment]
See: http://parseplatform.org/docs/parse-server/guide/#scalability

**Comment by AnChiChang** [comment]
I try to split Parse server and LiveQuery server, and base on document setup two servers like below, but, when ParseObject change, can't get Event. Could you advise what's wrong with the setting?


My Parse Server index.js setup like below:

    var api = new ParseServer({
      databaseURI: databaseUri || 'mongodb://192.168.200.45:27017/dev',
      cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
      appId: process.env.APP_ID || 'AppID',
      masterKey: process.env.MASTER_KEY || 'MasterKey', //Add your master key here. Keep it secret!
      //javascriptKey: process.env.JAVASCRIPT_KEY || '',
      serverURL: process.env.SERVER_URL || 'http://192.168.200.45:1111/parse',  // Don't forget to change to https if needed
      liveQuery: {
        classNames: ['ProductCount'],
        redisURL: 'redis://192.168.200.45:2222'
      },
    });
    var app = express();


    var port = process.env.PORT || 1111;
    var httpServer = require('http').createServer(app);
    httpServer.listen(port, function() {
        console.log('App on port ' + port + '.');
    });

    // This will enable the Live Query real-time server
    ParseServer.createLiveQueryServer(httpServer,  {
      redisURL: 'redis://192.168.200.45:2222'
    });


My LiveQuery Server setup like below:

    var express = require('express');
    var ParseServer = require('parse-server').ParseServer;
    var path = require('path');


    var api = new ParseServer({
      appId: process.env.APP_ID || 'AppID',
      masterKey: process.env.MASTER_KEY || 'MasterKey', //Add your master key here. Keep it secret!
      serverURL: process.env.SERVER_URL || 'http://192.168.200.45:1111/parse',  // Don't forget to change to https if needed
      websocketTimeout: 10 * 1000,
      cacheTimeout: 60 * 600 * 1000,
      logLevel: 'VERBOSE',
      liveQuery: {
        classNames: ['ProductCount'],
        redisURL: 'redis://192.168.200.45:2222'
      }
    });

    var app = express();

    var port = 2222;
    var httpServer = require('http').createServer(app);
    httpServer.listen(port, function() {
        console.log('LiveQuery Server running on port ' + port + '.');
    });

    // This will enable the Live Query real-time server
    ParseServer.createLiveQueryServer(httpServer,  {
      redisURL: 'redis://192.168.200.45:2222'
    });
