### ISSUE TITLE
Handlers never called

### ISSUE THREAD

**Issue by BRETT71** [parse-community/ParseLiveQuery-iOS-OSX#109]
Handle callbacks are never fired.

The live query server is working.  When I set up the same subscription using the Javascript LiveQuery SDK everything work.  When I use the iOS Live Query SDK all I am able to do is connect to the live server.

here is my code for iOS

```
let liveQueryClient = ParseLiveQueryClient(server: "https://domain/path")
Message.registerSubclass()
let querym = Message.query()
let subscribe = liveQueryClient.subscribe(querym!).handle(Event.created) { _, message in
     print("A message was created")
}
```

I am running the ws on a nginx server but I know that I have it setup correctly.
ParseLiveQuery: version 2.0.0
ParseiOSSDK: version 1.14.4
Parse-Server: version 2.3.6

**Comment by flovilmart** [comment]
The subscription is not retained and destroyed when your function returns. You have to assign it to a parent object or something similar.
