### ISSUE TITLE
websocket did not connect (Invalid http upgrade) 

### ISSUE THREAD

**Issue by Mahmoudlh** [parse-community/ParseLiveQuery-iOS-OSX#110]
when i'm trying to subscribe a query, this error has occured : Error Domain=WebSocket Code=301 "Invalid HTTP upgrade" UserInfo={NSLocalizedDescription=Invalid HTTP upgrade.

Is there a problem with Starscream lib version 2.0.3?

**Comment by Mahmoudlh** [comment]
Any help will be appreciated

**Comment by Mahmoudlh** [comment]
It seems that this issue is fixed in version 2.0.4 of lib Starscream!!!

**Comment by ranhsd** [comment]
Can you post some code along with your question?

**Comment by magneticrob** [comment]
This happens whenever the backend dev on my project restarts the server. So it sounds like maybe you're losing connection at some point?

**Comment by chuninator** [comment]
Any solution to this?

**Comment by flovilmart** [comment]
We’ve asked for more informations, that possibly can be caused by many things from the client to your server.

**Comment by chuninator** [comment]
Gotcha... I've found a solution in the `parse-server` repo, issue #2610... AWS needs to have load balancer, and `nginx.config` file to open the web sockets to connect. Hopefully, this helps.

**Comment by mvoccola** [comment]
I am getting this issue as well using Back4App. Using all latest versions of ParseLiveQuery etc.... The LiveQuery is actually not working at all, either. My error code is 502, as shown below:

`ParseLiveQuery: WebSocket did disconnect with error: Optional(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 502))`

**Comment by flovilmart** [comment]
@mvoccola this is likely a server issue, as nothing has changed. Reach out to back4app for their support

**Comment by mvoccola** [comment]
I was able to resolve this. Incorrectly placed the global reference to `ParseLiveQuery.Client(server: "wss://myServer.io")` outside of scope of class.
