### ISSUE TITLE
Parse LiveQuery in Cloud Code

### ISSUE THREAD

**Issue by Samigos** [parse-community/ParseLiveQuery-iOS-OSX#112]
I have an iOS and android application, deployed in a Parse Server. Now, I want to use the LiveQuery SDK, from a cloud function!

Here's my cloud code:
```
Parse.Cloud.define("subscribeQueryFunction", function(request, response) {
    var query = new Parse.Query("Message");
    var subscription = query.subscribe();

    subscription.on("create", (object) => {
        response.success(object);
    });
});
```
And my Swift code:
```
override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        PFCloud.callFunction(inBackground: "subscribeQueryFunction", withParameters: nil) { (res: Any?, e: Error?) in
            print(res)
            print(e)
        }
    }
```

The thing is, that the client doesn't get a response! Although, I checked the logs and the subscription seems to be established:

```
2017-05-14T16:49:12.442Z - Ran cloud function subscribeQueryFunction for user D7FP3cts5p with:
  Input: {}
  Result: {"text":"hey","createdAt":"2017-05-14T16:49:12.412Z","updatedAt":"2017-05-14T16:49:12.412Z","objectId":"DXCiumOTal","__type":"Object","className":"Message"}
2017-05-14T16:49:11.101Z - Ran cloud function subscribeQueryFunction for user D7FP3cts5p with:
  Input: {}
  Result: {"text":"hey","createdAt":"2017-05-14T16:49:11.044Z","updatedAt":"2017-05-14T16:49:11.044Z","objectId":"qkXS6csCKJ","__type":"Object","className":"Message"}
2017-05-14T16:49:09.099Z - Ran cloud function subscribeQueryFunction for user D7FP3cts5p with:
  Input: {}
  Result: {"text":"hey","createdAt":"2017-05-14T16:49:09.080Z","updatedAt":"2017-05-14T16:49:09.080Z","objectId":"ydnrDHO9AP","__type":"Object","className":"Message"}
2017-05-14T16:47:45.183Z - Create new client: 0
```

Any ideas?

**Comment by flovilmart** [comment]
AFAICT from the logs, the response should be sent to the client as you got Result: ... clearly in the logs.

**Comment by Samigos** [comment]
@flovilmart First of all, is what I'm trying to do possible? To receive live responses from a cloud function call?

**Comment by flovilmart** [comment]
Didn't try it nor would recommend it...

**Comment by Samigos** [comment]
Why wouldn't you? Also, I've been trying the last 5 hours to find a tutorial, or even just some code, showing how to subscribe and handle queries in Swift 3, but with no luck! Can you please help me out?

**Comment by Samigos** [comment]
Also, I've been trying the last 5 hours to find a tutorial, or even just some code, showing how to subscribe and handle queries in Swift 3, but with no luck! Can you please help me out?

**Comment by flovilmart** [comment]
Did you check the examples in the repository ?

**Comment by flovilmart** [comment]
Like: https://github.com/parse-community/ParseLiveQuery-iOS-OSX/tree/master/Examples/LiveQueryDemo

**Comment by Samigos** [comment]
Thank you very much! I finally made it work!

**Comment by HudiDev** [comment]
> Didn't try it nor would recommend it...

why wouldn't you recommend it?? in my case I need to retrieve data from db for swift client via a cloud function, so how do I go about live queries with PFCloud??

**Comment by flovilmart** [comment]
> in my case I need to retrieve data from db for swift client via a cloud function, so how do I go about live queries with PFCloud??

live queries are made to subscribe to queries not functions. If this is a feature you want to implement, you can open a PR.

**Comment by HudiDev** [comment]
> > in my case I need to retrieve data from db for swift client via a cloud function, so how do I go about live queries with PFCloud??
> 
> live queries are made to subscribe to queries not functions. If this is a feature you want to implement, you can open a PR.

so from what I understand, if I need to retrieve data via PFCloud from parse server - I will have to currently give up completely on real-time data. or is there still some kinda workaround..

**Comment by flovilmart** [comment]
One of the workaround is for you to allow subscribing to cloud function results by implementing it on this project. What do you say? It’s a good workaround 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NSAlemu** [comment]
> allow subscribing to cloud function results by implementing it on this project

Could you explain how that would work a bit more?
I decided to use cloud code for all querying. But I really don't want to lose livequery.
