### ISSUE TITLE
Live query for iOS is not work fine

### ISSUE THREAD

**Issue by youngerong** [parse-community/ParseLiveQuery-iOS-OSX#117]
I tried the live query demo for iOS, in the main.swift, both subscribeToUpdates(created event) and subscribeToModify(updated event), but only the subscribeToModify is valid, so I delete subscribeToModify, then the subscribeToUpdates become valid. So I guess only the latest subscribe function is valid.
But I tried the live query for js, both create and modify event work fine.

**Comment by chuninator** [comment]
Did you try implementing on your own and run into any issues? 
Parse's demos have never been quite the best... Share more so the community can help!
