### ISSUE TITLE
withinGeoBox not working

### ISSUE THREAD

**Issue by dplewis** [parse-community/ParseLiveQuery-iOS-OSX#120]
I keep receiving the following error when I use withinGeoBox
and crashes on Client.sendOperationAync. My guess is that it can't convert the PFGeoPoint to json to send for a subscribe.

```
PFQuery *query = [PFQuery queryWithClassName:@"TestObject"];
PFGeoPoint *sw = [PFGeoPoint geoPointWithLatitude:0.0 longitude:0.0];
PFGeoPoint *ne = [PFGeoPoint geoPointWithLatitude:10.0 longitude:10.0];
[query whereKey:@"location" withinGeoBoxFromSouthwest:sw toNortheast:ne];
    
_subscription = [_liveQueryClient subscribeToQuery:query];
```

```
'NSInvalidArgumentException', reason: 'Invalid type in JSON write (PFGeoPoint)'
```

**Comment by flovilmart** [comment]
it's highly possible that this encoding is not supporter, I really need to extract encoders/decoders from the iOS SDK and expose them for the liveQuery SDK.

**Comment by dplewis** [comment]
That would be great. On a side note how hard would it be to have withinPolygon supported by live query? If you point me in the right direction I can get it working. 

Can you make a TROUBLESHOOT.md? I use AWS and it took a lot of digging to get it working. And I see a lot of people having problems.

**Comment by flovilmart** [comment]
> I use AWS and it took a lot of digging to get it working

yeah, most issues arise with deployments on 3rd party, this is so specific, that I wonder if it can even start to cover. I know @ranhsd started a series of posts on deploying to GCP, (linked in the wiki).

> withinPolygon supported by live query

not really, liveQuery just does a synchronous matching, we just need an efficient [`point in polygon`](https://en.wikipedia.org/wiki/Point_in_polygon) algorithm for that.

**Comment by dplewis** [comment]
> not really, liveQuery just does a synchronous matching, we just need an efficient point in polygon algorithm for that.

https://github.com/substack/point-in-polygon Looks good might have to tweak it for double precision
Does this go in LiveQuery/QueryTools.js

> yeah, most issues arise with deployments on 3rd party, this is so specific, that I wonder if it can even start to cover. I know @ranhsd started a series of posts on deploying to GCP, (linked in the wiki).

The troubleshoot could be community based all in one location. But the wiki might be better as few people look at the wiki.

Retaining pointers isn't documented anywhere, I had to learn the hard way

**Comment by flovilmart** [comment]
> Looks good might have to tweak it for double precision
Does this go in LiveQuery/QueryTools.js

We are very cautious about 3rd party libs, this one in particular is unmaintained. 

> Retaining pointers isn't documented anywhere

If you mean the fact that the subscription is not retained by default, that's actually by design, otherwise, memory management would be impossible :)

**Comment by flovilmart** [comment]
Another avenue for more complex queries would be to support asynchronous query resolution in the QueryTools, so we'll have a synchronous 'shortcut' for obvious values and DB / query driven resolution for more complex queries. Those queries would be more 'pricey' but also will help us support inclusion etc...

**Comment by dplewis** [comment]
> We are very cautious about 3rd party libs, this one in particular is unmaintained.

I wouldn't add it as a dependency and its one function. I'll give him credit.

>  Another avenue... 

$inQuery sounds like fun

> In you mean the fact that subscription...

Should be documented somewhere, it's good to know


Sorry on an iPhone and bad English

**Comment by flovilmart** [comment]
> Should be documented somewhere

`client.subscribe(query: query)` returns an unretained object, (which kinda makes sense) but we could rename to `createSubscription`, or remove it altogether, with something like:

```
let subscription = Subscription(client: client, query: query)
// Now you know that your sub is not retained!
```

I understand that the terminology is confusing, (calling subscribe implies a side-effect)

**Comment by dplewis** [comment]
Time for me to learn swift :)

**Comment by dplewis** [comment]
Somebody already made a PR for extracting the encoder/decoder.

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1029

**Comment by flovilmart** [comment]
This PR needs rebase and has failings tests:/

**Comment by flovilmart** [comment]
~The latest release should be working with that as expected.~ 

My bad we extracted the encoders for the objects not the queries.

**Comment by noobs2ninjas** [comment]
This has been open forever. I think we've addressed this with an update yes?

**Comment by dplewis** [comment]
It hasn’t unfortunately

**Comment by dplewis** [comment]
Let me try to provide a fix for it. I should learn swift anyway.

**Comment by noobs2ninjas** [comment]
That would be fantastic. If you're used to Obj-C then in comparison Swift may feel like complete chaos with its noncolon, anti-parenthesis, and closure/lambda obsessed way of doing things. Dont get me wrong. It will be easy. But when I made the move it felt like I was unlearning everything I had ever been taught.
