### ISSUE TITLE
Subscribe to a range of events at once?

### ISSUE THREAD

**Issue by Samigos** [parse-community/ParseLiveQuery-iOS-OSX#121]
Is it possible to subscribe e.g. to create and update events, in one subscription?

**Comment by flovilmart** [comment]
All events are subscribed by default, you can choose to not set a handler for Those events in your code, or implement all event handlers

**Comment by Samigos** [comment]
@flovilmart Thanks for the response! How can I not set the Event type? I don't see any method with that property optional...

**Comment by Samigos** [comment]
Ok! Found it!

    `subscription = liveQueryClient.subscribe(chatRoomQuery)
  
     _ = subscription?.handleEvent { query, event in
            print(query)
            print(event)
        }`

Thanks!

**Comment by flovilmart** [comment]
I don't get your question, do you have a code example?
