### ISSUE TITLE
Parse Live Query not delivering updates when app is running in background mode

### ISSUE THREAD

**Issue by rafaelmaroxa** [parse-community/ParseLiveQuery-iOS-OSX#122]
I noticed that the Android PLQ library allows for the updates to be delivered while the app is in background mode. The PLQ iOS library holds the events and only delivers them after the app comes back to the foreground.

Is this a bug or desired behavior of the PLQ iOS library?

Thanks in advance.

**Comment by vexelgray** [comment]
Same problem here... did you find some solution @rafaelmaroxa?

**Comment by rafaelmaroxa** [comment]
I didn't, @vexelgray. In my case, I have the app running with `location` set correctly in the `Info.plist` file under `UIBackgroundModes`. My app runs in the background just fine, but PLQ updates are still not being delivered.

**Comment by chuninator** [comment]
Did we find any more info on this?

**Comment by flovilmart** [comment]
Not sure if you can maintain a network connection in background for a long time on iOS. For those, you should use push notifications
