### ISSUE TITLE
websocketDidDisconnect(socket:error:) prints lots logs

### ISSUE THREAD

**Issue by ananfang** [parse-community/ParseLiveQuery-iOS-OSX#128]
If the device disconnected from the WebSocket, the delegate will trigger **func websocketDidDisconnect(socket:error:)**, and print lots of logs by:
`print("error: \(error)")`

It is not ideal for release build, so this pull request adds a property **"shouldPrintWebSocketLog" for class Client**. By default this value is true, and you can turn the logs off by setting it false.

Here is my [pull request](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/126) about this issue.

**Comment by flovilmart** [comment]
Thanks for the PR! Closing as resolved!

**Comment by ananfang** [comment]
Thanks for @flovilmart review!

**Comment by flovilmart** [comment]
sorry it took forever!
