### ISSUE TITLE
Provide Swift LiveQuery use case example for Realtime Messaging

### ISSUE THREAD

**Issue by otymartin** [parse-community/ParseLiveQuery-iOS-OSX#13]
#### Environment Setup

MongoLab(mLab), Google App Engine...
@wangmengyan95 @richardjrossiii 

Since iOS docs aren't released yet i'm still struggling to implement live queries on the client side.
So I'd like to get an example for how it could be use to send/recieve realtime messages in a messaging app using a method I'm using in my own chat app which was previously using push notifications.

How could I implement liveQueries in this method to send/receive realtime messages?

``` swift
// MARK: - LOAD MESSAGES
    func loadMessages() {

        print("Loading messages...")
        var lastMessage:JSQMessage? = nil

        if messages.last != nil {
            lastMessage = messages.last
        }

        let messageQuery = PFQuery(className: "Message")
        messageQuery.whereKey("room", equalTo: self.room!)
        messageQuery.orderByAscending("createdAt")
        messageQuery.limit = 500
        messageQuery.includeKey("user")

        if lastMessage != nil {
            messageQuery.whereKey("createdAt", greaterThan: lastMessage!.date)
        }

        messageQuery.findObjectsInBackgroundWithBlock { (results: [PFObject]?, error:NSError?) -> Void in

            if error == nil {

                if results != nil {

                    let messages = results

                    for message in messages! {

                        self.messageObjects.append(message)

                        let user = message["user"] as! PFUser
                        self.users.append(user)

                        let chatMessage = JSQMessage(senderId: user.objectId , displayName: user.objectForKey("name") as! String, text: message["content"] as! String)
                        self.messages.append(chatMessage)

                        Answers.logCustomEventWithName("Messages Loaded", customAttributes: nil)

                    }
                }

                if results?.count != 0 {
                    self.finishReceivingMessage()
                }

            }
        }

    }
```

Don't think my send method is needed but here it is either way.

``` swift
   //MARK: - SEND MESSAGES
    override func didPressSendButton(button: UIButton!, withMessageText text: String!, senderId: String!, senderDisplayName: String!, date: NSDate!) {

        let message = PFObject(className: "Message")
        message["content"] = text
        message["room"] = self.room
        message["user"] = PFUser.currentUser()

        message.saveInBackgroundWithBlock { (success: Bool, error:NSError?) -> Void in

            if error == nil {

                self.loadMessages()
                //self.sendPushToContact()
                self.room!["lastUpdate"] = NSDate()
                self.room?.saveInBackgroundWithBlock(nil)
                Answers.logCustomEventWithName("Send Message", customAttributes: nil)

            } else {

                print("Error while sending message \(error?.localizedDescription)")
            }
        }
        self.finishSendingMessage()
    }
```

**Comment by Eke** [comment]
@otymartin i'll try to explain with my bad english : ))

In provided example  ([here](https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/blob/master/Examples/LiveQueryDemo/main.swift)) is same flow as you want. So first of all you must store reference to your `PFQuery`, `Subscription` and LiveQuery client.

```
let liveQueryClient = ParseLiveQuery.Client(server: "http://localhost:1337") 

private var subscription: Subscription<Message>?
var messagesQuery: PFQuery {
        return (Message.query()?
            .whereKey("room_name", equalTo: currentChatRoom!.name!)
            .orderByAscending("createdAt"))!
    }
```

After this you can subscribe to this `PFQuery`, this happens like this:

```
    func subscribeToUpdates() {
        subscription = liveQueryClient
            .subscribe(messagesQuery)
            .handle(Event.Created) { _, message in
                self.printMessage(message)
        }
    }
```

So each time objects is added to database, and this object matches this `PFQuery`, you will receive `Create` event (`handle(Event.Created)`) and `self.printMessage(message)` will be called.

Now about saving `PFObject`, you don't need to send any push notification or something like this. Just save `PFObject` for example with `saveInBackgroundWithBlock`, as soon as it is saved all subscribed clients will be notified about new object created.

**Comment by otymartin** [comment]
@Eke I've been really trying to avoid publicly embarrassing myself but I tried and failed. Basically, My code is very beginner and simple. Its not modular at all, it flows like the magna carter (as you can see above😂) so I couldn't follow your flow or that of the example eg. This syntax is totally alien to me 

``` swift
var subscription: Subscription<Message>?
```

I omitted 

``` swift
let liveQueryClient = ParseLiveQuery.Client(server: "http://localhost:1337") 
```

because somewhere I read if I dont specify, it will pull the url from my server.js. which is "https://myAppName.appspot.com/parse".

So I tried to translate

``` swift
        let messageQuery = PFQuery(className: "Message")
        messageQuery.whereKey("room", equalTo: self.room!)
        messageQuery.orderByAscending("createdAt")
        //messageQuery.limit = 500
        messageQuery.includeKey("user")

        messageQuery.subscribe().handle(Event.Created) { _, message in
            self.messageObjects.append(message)
            let user = message["user"] as! PFUser
            self.users.append(user)
            let chatMessage = JSQMessage(senderId: user.objectId , displayName: user.objectForKey("name") as! String, text: message["content"] as! String)
            self.messages.append(chatMessage)
        }
```

Needless to say, it failed miserably.

```
Error: Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 400" UserInfo={NSLocalizedDescription=received bad response code from server 400, HTTPResponseStatusCode=400}
```

**Comment by Eke** [comment]
@otymartin it is your server side error. maybe websocket or some ports are not enabled on your server. If your are using google App Engine, try to look at it's documentation how to enable websockets

**Comment by otymartin** [comment]
@Eke 

Is my server setup properly? Note my port is 8080, im not entirely sure what the port is supposed to be.

``` javascript
var port = process.env.PORT || 8080;
var httpServer = http.createServer(app);
httpServer.listen(port, function() {
  console.log('parse-server-example running on port ' + port + '.');
});

// Initialize a ParseLiveQuery server instance
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer, {
  logLevel: 'VERBOSE',
  keyPairs: {
    javascriptKey: 'test'
  }
});
```

**Comment by richardjrossiii** [comment]
@otymartin if your port is something other than the HTTP default port, you'll definitely need to set the server URL yourself. 

For the record - we can only autodetect the URL if you've already configured `Parse` using a custom `ParseClientConfiguration`. We can't detect anything from your server automatically.

**Comment by FredvanRijswijk** [comment]
@otymartin  Do you have found a solution? And how do you bind / insert the new data into your collection or tableview?

**Comment by otymartin** [comment]
@FredvanRijswijk Hey I never ended up using them as the use-case I had in my didn't warrant the effort of setting it up on second thought. However In the future I will need it. For now I'm sticking to regular queries

**Comment by FredvanRijswijk** [comment]
@Eke @richardjrossiii  Do you have an example for a use in combination with a TableView or CollectionView? How to bind and insert new data ? It's working, [https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/38](https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/38) but i'm really confused how to this the right way, because a test thats working it's really with inserting the table row.

**Comment by Eke** [comment]
@FredvanRijswijk yes i have Objective-c example with CollectionView.

**Comment by FredvanRijswijk** [comment]
@Eke Can you share this Objective-C example with the LiveQuery query and how the data is put in this CollectionView ? Thnx Is hard to make that convert to swift?

**Comment by Eke** [comment]
Sure @FredvanRijswijk, can send you files, check my email on my profile page and email me.

**Comment by FredvanRijswijk** [comment]
@Eke I have send you an email, thnx

**Comment by otymartin** [comment]
@FredvanRijswijk Mind sharing it here. Would be useful for me and others in the future thanks ;)

**Comment by FredvanRijswijk** [comment]
Yes, I'm making an example in swift like this [https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/38](https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/38)

**Comment by FredvanRijswijk** [comment]
[https://gist.github.com/FredvanRijswijk/bb131ddc67d11a2441469513d30a501a](https://gist.github.com/FredvanRijswijk/bb131ddc67d11a2441469513d30a501a) I have this now.... but is not working for now ;-(
