### ISSUE TITLE
Live Query client doesn't account for server protocol of wss

### ISSUE THREAD

**Issue by JoeSzymanski** [parse-community/ParseLiveQuery-iOS-OSX#134]
If the Live Query client is initialized with a URL that already uses the wss scheme, it improperly downgrades to a non-secure ws connection. See https://github.com/parse-community/ParseLiveQuery-iOS-OSX/blob/master/Sources/ParseLiveQuery/Client.swift#L54

This line should be updated to check for a scheme of wss in addition to https.

**Comment by flovilmart** [comment]
@JoeSzymanski are you willing to open a PR for it?

**Comment by JoeSzymanski** [comment]
I'll take a look at that shortly to make a basic fix.

**Comment by flovilmart** [comment]
Thanks!

**Comment by flovilmart** [comment]
Closing as resolved.
