### ISSUE TITLE
Can't remove the 'sessionToken' field of a PFUser

### ISSUE THREAD

**Issue by Eke** [parse-community/ParseLiveQuery-iOS-OSX#14]
Hello,

In my app i have location field in PFUser object. Application crashes with error `Can't remove the 'sessionToken' field of a PFUser` when update event is received.

any ideas? tried to debug but no result

@nlutsenko @richardjrossiii

**Comment by Eke** [comment]
UPD:

Added `key != "sessionToken"` `private func parseObject<T: PFObject>` in ClientPrivate.swift so it looks like this now :

```
private func parseObject<T: PFObject>(objectDictionary: [String:AnyObject]) throws -> T {
    guard let parseClassName = objectDictionary["className"] as? String else {
        throw LiveQueryErrors.InvalidJSONError(json: objectDictionary, expectedKey: "parseClassName")
    }
    guard let objectId = objectDictionary["objectId"] as? String else {
        throw LiveQueryErrors.InvalidJSONError(json: objectDictionary, expectedKey: "objectId")
    }

    let parseObject = T(withoutDataWithClassName: parseClassName, objectId: objectId)

    objectDictionary.filter { key, _ in
        key != "parseClassName" && key != "objectId" && key != "sessionToken"
        }.forEach { key, value in
            parseObject[key] = value
    }

    return parseObject
}
```

At this moment everything works good, but i don't know if sessionToken is required field for PFUser in this case.

**Comment by richardjrossiii** [comment]
Good catch. We should have checked for 'sessionToken' as a key as well. I'll send a PR to fix shortly.
