### ISSUE TITLE
Invalid type in Json

### ISSUE THREAD

**Issue by djaygit** [parse-community/ParseLiveQuery-iOS-OSX#141]
It keeps crashing with 2.2.1 with 

'NSInvalidArgumentException', reason: 'Invalid type in JSON write (MyApp.ParseUser)'

when i call 
 let postQuery = PFQuery(className: "PostedRequests")
 postQuery.whereKey("byUser", notEqualTo: PFUser.current()!)
let postQuerySubs = ParseLiveQuery.Client.shared.subscribe(postQuery)

Crashes on ClientPrivate.swift line 200 
let jsonData = try JSONSerialization.data(withJSONObject: jsonEncoded, options: JSONSerialization.WritingOptions(rawValue: 0))

**Comment by ghost** [comment]
Same here. Has anyone found a fix?

**Comment by flovilmart** [comment]
Can you provide more informations like the dump of the `jsonEncoded`?
