### ISSUE TITLE
Unsubscribe didn't work

### ISSUE THREAD

**Issue by iThinkersTeam** [parse-community/ParseLiveQuery-iOS-OSX#146]
When user login I use subscriptions when he log out I make unsubscribe.
When another user login to app subscription didn't work.

I checked liveQueryClientBox.subscriptions and it is always keep subscription.

Any idea how I can fix it?

**Comment by flovilmart** [comment]
Can you provide some code please?

**Comment by iThinkersTeam** [comment]
Sure

This my subscribe functions
func liveQueryAreas() {
        guard let username = PFUser.current()?.username else { return }
        Functions.addNotificationBanner(title: "Add Live Query")
        areaQuery = (Area.query()?
            .whereKey("username", equalTo: username)
            .order(byDescending: "updatedAt")) as! PFQuery<Area>

        areaSubscription = liveQueryClientArea.subscribe(areaQuery).handle(Event.updated, { (_, area) in
            Functions.addNotificationBanner(title: "Live Query updated Area")
            self.parse(area: area, type: .updated)
        }).handle(Event.created, { (_, area) in
            Functions.addNotificationBanner(title: "Live Query created Area")
            self.parse(area: area, type: .created)
        }).handle(Event.deleted, { (_, area) in
            Functions.addNotificationBanner(title: "Live Query created Area")
            self.parse(area: area, type: .deleted)
        })
    }

this functions for unsubscribe
I tried 3 different way
    func unsubscribe() {
        guard let _ = PFUser.current()?.username else { return }
        liveQueryClientArea.unsubscribe(areaQuery, handler: areaSubscription!.handle(Event.updated, { (_, _) in
            print("unsubscribe upadte")
        }))
        liveQueryClientArea.unsubscribe(areaQuery as! PFQuery<PFObject>)
        liveQueryClientBox.unsubscribe(boxQuery, handler: boxSubscription!)
        
        liveQueryClientItem.unsubscribe(itemQuery, handler: itemSubscription!)
        liveQueryClientUser.unsubscribe(userQuery, handler: userSubscription!)
        areaSubscription = nil
        boxSubscription = nil
        itemSubscription = nil
        userSubscription = nil
    }

**Comment by flovilmart** [comment]
I believe we shipped a fix for this particular issue in the latest version, can you try it?

**Comment by iThinkersTeam** [comment]
When I try install last version ParseLiveQuery the ParseFacebookUtilsV4 automatically decreases to version 1.11.1, and I got error No known class method for selector 'taskWithException:' in ParseFacebookUtilsV4. This issue fixed in version 1.11.2

Any idea how I can fix it?

**Comment by flovilmart** [comment]
With the latest version of the Parse SDK through cocoapods, Facebook utils is distributes alongside the Parse pod as a subspec.
Just remove ParseFacebookUtilsV4 pod, and add 

`pod ‘Parse/FacebookUtils’`

Then in your project you can remove all imports related to ParseFacebookUtils as it will be available part of the Parse imports
