### ISSUE TITLE
Swift 4 disconnection error

### ISSUE THREAD

**Issue by JoseVigil** [parse-community/ParseLiveQuery-iOS-OSX#150]
Hi, 

I upgraded my project to Swift 4 and LiveQuery is having a disconnection loop problem. 

`
CFNetwork SSLHandshake failed (-9806)
TCP Conn 0x60c000175900 SSLHandshake failed (-9806)
ParseLiveQuery: WebSocket did disconnect with error: Optional(Error Domain=NSOSStatusErrorDomain Code=-9806 "(null)" UserInfo={_kCFStreamErrorCodeKey=-9806, _kCFStreamErrorDomainKey=3})
`

As a note, I recall having this same exact issue when upgrading to 3.2 and then using 2.3.0 solved. Worst of the cases I can go back to Swift 3.2. 

Using Bolts (1.9.0)
Using Bolts-Swift (1.3.0)
Using Parse (1.16.0)
Using ParseLiveQuery (2.3.0)

Thanks very much in advance. 

Jose

**Comment by flovilmart** [comment]
Is your https cert valid /not self signed? Can you try without wss but just with the ws protocol?

**Comment by JoseVigil** [comment]
Hi flovilmart, 

Yes indeed there is no issue with "ws" protocol instead of "wss". 

I have not self signed https cert, can you please provide me some orientation?

BTW: I appreciate your dedication and commitment to the parse project, an undermined and powerful tool that hopefully lives long. 

Jose

**Comment by flovilmart** [comment]
Thanks @JoseVigil for the good words!

So if there's no issue with the ws protocol, it indicates that there's an issue with your certificate, or the configuration of the certificate on the server. Depending if you're using nginx, or apache or directly node the resolution will vary. Without more info, that's tough to make a diagnostic.

**Comment by JoseVigil** [comment]
Thanks very much, your answer was very clear and moving towards the right direction now.

**Comment by flovilmart** [comment]
If you have any insight to share here with the full resolution, that may be helpful to other users, don’t hesitate to write a follow up

**Comment by JoseVigil** [comment]
Indeed @flovilmart I will post the experience once I finish app functionality and set production backend.
