### ISSUE TITLE
Poor Connections

### ISSUE THREAD

**Issue by iThinkersTeam** [parse-community/ParseLiveQuery-iOS-OSX#152]
If I have problem with observer when I have poor connection. Observers stoped to work and only when I close the app and open again it fix observers.

Could you give me any suggestions how I can fix?

Thanks a lot

**Comment by iThinkersTeam** [comment]
We found error. It is problem Starscream in this code
if canDispatch {
                    DispatchQueue.main.async { [weak self] in
                        guard let s = self else { return }
                        s.onText?(str! as String)
                        s.delegate?.websocketDidReceiveMessage(socket: s, text: str! as String)
                    }
                }
In this case DispatchQueue.main.async closure ignore. 
Do you have any suggestion?

**Comment by flovilmart** [comment]
If he issue is in starscream you’ll probably need to open an issue on this repository
