### ISSUE TITLE
I got theses errors when i install ParseLiveQuery in a SwiftProject

### ISSUE THREAD

**Issue by ljs19923** [parse-community/ParseLiveQuery-iOS-OSX#153]
I got theses errors when i install ParseLiveQuery in a SwiftProject

![image](https://user-images.githubusercontent.com/5727223/35342414-49b1b500-0128-11e8-923a-379a5c8f9807.png)

![image](https://user-images.githubusercontent.com/5727223/35342432-54c9dea4-0128-11e8-9077-da524f29ed9c.png)

**Comment by flovilmart** [comment]
What version of Swift are you using? What version of LiveQuery are you using?

**Comment by ljs19923** [comment]
Swift 4.0  & the last LiveQuery
![image](https://user-images.githubusercontent.com/5727223/35342926-a1ef86d8-0129-11e8-9921-214b9a390674.png)

**Comment by ljs19923** [comment]
![image](https://user-images.githubusercontent.com/5727223/35343077-f91fc8d2-0129-11e8-87e6-84a83ef0e4bd.png)

**Comment by flovilmart** [comment]
Can you try with

```
  pod 'ParseLiveQuery', :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX', :branch => 'release-2.4.0'
  pod 'Parse', '~> 1.17.0-alpha.3'
```

**Comment by ljs19923** [comment]
Same Errors
![image](https://user-images.githubusercontent.com/5727223/35343459-ff9e8bac-012a-11e8-8f8c-63fe2bdf2c6d.png)
![image](https://user-images.githubusercontent.com/5727223/35343465-06657004-012b-11e8-8275-101f2ee14d0b.png)

**Comment by flovilmart** [comment]
Swift should be automatically forced to 3.0 as per the `.swift-version` file. what version of cocoapods are you using? double check that the pods projects are setting the SWIFT_VERSION to the same as the .swift-version file. Note that you can have a swift 4 main project and pods at swift 3.2 version.

**Comment by ljs19923** [comment]
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/lib/cocoapods.rb

So 1.4.0

**Comment by ljs19923** [comment]
I need to include this in my podfile ?

 post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end

**Comment by flovilmart** [comment]
Worth trying or set your project version to 3.X

**Comment by ljs19923** [comment]
I get the same error... 
I have to change my entire project in swift 3.X?

**Comment by ljs19923** [comment]
It does not make much sense to downgrade my version of Swift ...?

**Comment by flovilmart** [comment]
I'm not sure, check the demo projects in the repo, they both compile. Our main project is writting in Swift 4, uses cocoapods, and is properly compiling as well. I'm not sure what else I can suggest.

**Comment by felix-dumit** [comment]
I'm actually also getting this even after #154. I think the same needs to be done for `Bolts-Swift`, but the current `.swift-version` there is `4.0`

It is fixed if I do:
```ruby
post_install do | installer |
  installer.pods_project.targets.each do |target|
    if target.name.end_with? 'Bolts-Swift'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
```

**Comment by aliasad106** [comment]
Parse Live Query version 2.3.0 and Swift 4.2 gives the same issues. Installed with pod
