### ISSUE TITLE
Project build failed while using Carthage build 

### ISSUE THREAD

**Issue by bayareahank** [parse-community/ParseLiveQuery-iOS-OSX#155]
Build example app (and other ones using liveQuery) failed after carthage build. 

Setup: 
swift 4.0
xcode 9.2
carthage 0.28.0

cat Cartfile
github "ParsePlatform/ParseLiveQuery-iOS-OSX" "2.3.0"

cat Cartfile.resolved 
github "BoltsFramework/Bolts-ObjC" "1.9.0"
github "BoltsFramework/Bolts-Swift" "1.3.0"
github "ParsePlatform/Parse-SDK-iOS-OSX" "1.16.0"
github "ParsePlatform/ParseLiveQuery-iOS-OSX" "2.3.0"
github "daltoniam/Starscream" "3.0.4"
github "daltoniam/common-crypto-spm" "1.1.0"
github "daltoniam/zlib-spm" "1.1.0"

Carthage build of frameworks is fine, yet when trying to build the project, it will report duplicate definition errors like below. Checking files under Carthage/Checkouts, we would find there is a duplicate copy of every libraries used by ParseLiveQuery, one is under ./Checkouts directly, another is under ./Checkouts/ParseLiveQuery-iOS-OSX/Carthage/Checkouts. Looks to me like dependency management problem. 
 

/liveQuery/Carthage/Checkouts/Starscream/zlib/module.modulemap:1:8: error: redefinition of module 'SSCZLib'
module SSCZLib [system] {
       ^
/liveQuery/Carthage/Checkouts/ParseLiveQuery-iOS-OSX/Carthage/Checkouts/Starscream/zlib/module.modulemap:1:8: note: previously defined here
module SSCZLib [system] {
       ^
/liveQuery/Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: error: redefinition of module 'SSCommonCrypto'
module SSCommonCrypto [system] {
       ^
/liveQuery/Carthage/Checkouts/ParseLiveQuery-iOS-OSX/Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: note: previously defined here
module SSCommonCrypto [system] {
       ^
<unknown>:0: error: could not build Objective-C module 'Starscream'

**Comment by flovilmart** [comment]
We'll have a look!

**Comment by bayareahank** [comment]
Indeed it looks like a dependency management issue. 

I get a copy of my old Cartfile.resolved whose build works, it looks pretty clean: 

github "ParsePlatform/Parse-SDK-iOS-OSX" "master"
github "ParsePlatform/ParseLiveQuery-iOS-OSX" == 2.0.0

While the new Cartfile.resolved has all these dependent libs that should be hidden in lower levels, which caused duplicate definitions at project build time.

**Comment by flovilmart** [comment]
can you try with Parse-SDK-iOS-OSX master and ParseLiveQuery-iOS-OSX on release-2.4.0

**Comment by bayareahank** [comment]
It shows the same duplicated definition errors with release-2.4.0 and Parse master. 

Indeed I tried down to 2.2.2, the result is the same. 

Last time I worked with this is in last Aug. with 2.0.0. I roughly remember that is also a work around (by using Parse master), as you can see from the Cartfile at that time: 

github "ParsePlatform/Parse-SDK-iOS-OSX" "master"
github "ParsePlatform/ParseLiveQuery-iOS-OSX" == 2.0.0

Naturally it doesn't work any more with 2.0.0. 

One thing I want to know is: has any one else run into something similar, or am I the only one using pure Carthage build here? I start to seriously doubt myself at this moment :).

**Comment by bayareahank** [comment]
Duplicates of 159
