### ISSUE TITLE
Archive Frameworks With Release

### ISSUE THREAD

**Issue by eduardo22i** [parse-community/ParseLiveQuery-iOS-OSX#158]
Hey hi,

I'm using Carthage. Is it possible, that you guys archive the prebuilt frameworks and attach them on each release?

https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

Thanks!

**Comment by flovilmart** [comment]
Swift is not ABI stable and therefore, the compiled binaries may be broken depending which version of Swift you’re targeting and which version of Swift the binary framework has been produced with. We’ll not bother with this at the moment, but may very well when Swift 5 gets released (if ABI stable)
