### ISSUE TITLE
Some times I have strange crashes. 

### ISSUE THREAD

**Issue by alecsechechel** [parse-community/ParseLiveQuery-iOS-OSX#160]
Hello, some time I or my client have crashes, it is very difficult reproduce and I din't find any logic of it. I add files from my crashlytics, maybe it helps recognize where is issues.

[Unknown-6.txt](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/files/2029837/Unknown-6.txt)
[Unknown-5.txt](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/files/2029838/Unknown-5.txt)

Thanks a lot

**Comment by flovilmart** [comment]
can you provide the symbolicated symbols as it stands there is no clue in the crash about the nature or the reason for the exception
