### ISSUE TITLE
Could not cast value of type 'PFQuery' to 'PFQuery' 

### ISSUE THREAD

**Issue by ferrinho** [parse-community/ParseLiveQuery-iOS-OSX#161]
Usinge version 2.4.0 and get the error when trying to subscribe.

**Comment by flovilmart** [comment]
Please provide a full stacktrace

**Comment by ferrinho** [comment]
29 elements
  - 0 : "0   ???                                 0x000000013502941a 0x0 + 5184328730"
  - 1 : "1   ???                                 0x00000001350294d5 0x0 + 5184328917"
  - 2 : "2   IRON TRAINERS                       0x000000010a8436a0 main + 0"
  - 3 : "3   libsystem_c.dylib                   0x00000001153f0c97 abort + 127"
  - 4 : "4   libswiftCore.dylib                  0x000000011449efe5 _ZN5swift10fatalErrorEjPKcz + 149"
  - 5 : "5   libswiftCore.dylib                  0x0000000114497d0b _ZN5swift24swift_dynamicCastFailureEPKvPKcS1_S3_S3_ + 75"
  - 6 : "6   libswiftCore.dylib                  0x0000000114497d70 swift_dynamicCastClass + 0"
  - 7 : "7   libswiftCore.dylib                  0x00000001144d4d9e swift_dynamicCastObjCClassUnconditional + 62"
  - 8 : "8   ParseLiveQuery                      0x000000010c060b62 _T014ParseLiveQuery6ClientC18SubscriptionRecordCAESo7PFQueryCy16PFObjectSubclassQzG5query_AC9RequestIdV07requestL0x7handlertcAA0E8HandlingRzlufc + 258"
  - 9 : "9   ParseLiveQuery                      0x000000010c060a0d _T014ParseLiveQuery6ClientC18SubscriptionRecordCAESo7PFQueryCy16PFObjectSubclassQzG5query_AC9RequestIdV07requestL0x7handlertcAA0E8HandlingRzlufC + 93"
  - 10 : "10  ParseLiveQuery                      0x000000010c05d55e _T014ParseLiveQuery6ClientC9subscribexSo7PFQueryCy16PFObjectSubclassQzG_x7handlertAA20SubscriptionHandlingRzlF + 302"
  - 11 : "11  ParseLiveQuery                      0x000000010c06d37f _T014ParseLiveQuery6ClientC18_PF_objc_subscribeAA31ObjCCompat_SubscriptionHandling_pSo7PFQueryCySo8PFObjectCG_AaE_p7handlertF + 127"
  - 12 : "12  ParseLiveQuery                      0x000000010c06d411 _T014ParseLiveQuery6ClientC18_PF_objc_subscribeAA31ObjCCompat_SubscriptionHandling_pSo7PFQueryCySo8PFObjectCG_AaE_p7handlertFTo + 81"
  - 13 : "13  ParseLiveQuery                      0x000000010c06d47f _T014ParseLiveQuery6ClientC18_PF_objc_subscribeAA10ObjCCompatV12SubscriptionCSo7PFQueryCySo8PFObjectCGF + 79"
  - 14 : "14  ParseLiveQuery                      0x000000010c06d4fc _T014ParseLiveQuery6ClientC18_PF_objc_subscribeAA10ObjCCompatV12SubscriptionCSo7PFQueryCySo8PFObjectCGFTo + 60"
  - 15 : "15  IRON TRAINERS                       0x000000010a99e6e7 __28-[TeamChatTVC queryForTable]_block_invoke + 2583"
  - 16 : "16  IRON TRAINERS                       0x000000010aa620d2 __72-[BFTask(Private) continueWithMainThreadResultBlock:executeIfCancelled:]_block_invoke + 162"
  - 17 : "17  IRON TRAINERS                       0x000000010a9e718f __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 91"
  - 18 : "18  libdispatch.dylib                   0x00000001152a0807 _dispatch_call_block_and_release + 12"
  - 19 : "19  libdispatch.dylib                   0x00000001152a1848 _dispatch_client_callout + 8"
  - 20 : "20  libdispatch.dylib                   0x00000001152ac92b _dispatch_main_queue_callback_4CF + 628"
  - 21 : "21  CoreFoundation                      0x00000001128f2c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9"
  - 22 : "22  CoreFoundation                      0x00000001128b6ea6 __CFRunLoopRun + 2342"
  - 23 : "23  CoreFoundation                      0x00000001128b630b CFRunLoopRunSpecific + 635"
  - 24 : "24  GraphicsServices                    0x0000000117b5ea73 GSEventRunModal + 62"
  - 25 : "25  UIKit                               0x000000010fe2a0b7 UIApplicationMain + 159"
  - 26 : "26  IRON TRAINERS                       0x000000010a84370f main + 111"
  - 27 : "27  libdyld.dylib                       0x000000011531e955 start + 1"
  - 28 : "28  ???                                 0x0000000000000001 0x0 + 1"

**Comment by flovilmart** [comment]
And the code please.

**Comment by ferrinho** [comment]
Sorry. 

Here's how I'm trying to subscribe:

`self.subscription = [singleton.liveQueryClient subscribeToQuery:self.messageQuery];
                
                __weak typeof(self) weakSelf = self;
                [self.subscription addCreateHandler:^(PFQuery<PFObject *> * _Nonnull query, PFObject * _Nonnull object) {
                    // The actions to handle the object that is incoming go here
                    NSLog(@"MESSAGE CREATED");
                    weakSelf.messageQuery = query;
                    NSLog(@"object: %@", object);
                    //[weakSelf fetchMessagesAgain];
                }];
                [self.subscription addUpdateHandler:^(PFQuery<PFObject *> * _Nonnull query, PFObject * _Nonnull object) {
                    // The actions to handle the object that is incoming go here
                    NSLog(@"MESSAGE CREATED 2");
                    NSLog(@"object: %@", object);
                    weakSelf.messageQuery = query;
                    //[weakSelf fetchMessagesAgain];
                }];`

And initializing:

`if (!self.liveQueryClient) {
        self.liveQueryClient = [[PFLiveQueryClient alloc]  initWithServer:Parse.currentConfiguration.server
                                                                        applicationId:@"appid"
                                                                            clientKey:@"clientKey"];
    }`

And the crash as in the picture. Thanks.

![screen shot 2018-05-24 at 20 35 31](https://user-images.githubusercontent.com/13586732/40509740-62057e02-5f92-11e8-9279-36b5efbd0cbb.png)

**Comment by flovilmart** [comment]
and what is `self.messageQuery ?` From what I can see it looks like it can't cast the query from Obj-C to Swift. Can you show the variables from the left panel?

**Comment by ferrinho** [comment]
![screen shot 2018-05-24 at 20 52 26](https://user-images.githubusercontent.com/13586732/40510371-66043848-5f94-11e8-86da-7487e6c85b3b.png)

**Comment by ferrinho** [comment]
self.messageQuery = [PFQuery queryWithClassName:@"StaffITMessages"];

**Comment by ferrinho** [comment]
this one is before trying to subscribe:

![screen shot 2018-05-24 at 20 56 33](https://user-images.githubusercontent.com/13586732/40510619-2bbe81e2-5f95-11e8-8f88-5ff1d158401d.png)

**Comment by flovilmart** [comment]
I cannot reproduce with the demo project. I'm not sure how this can happen.

What version of the Parse SDK are you using? What version of the LiveQuery SDK are you using? How did you get those SDK's (cocoapods, Carthage etc..)?

**Comment by ferrinho** [comment]
The following is my podfile, I had to add cocoapods to my project in order to make it work with LiveQuery... we didn't use it up until now. 

PODS:
  - Bolts (1.9.0):
    - Bolts/AppLinks (= 1.9.0)
    - Bolts/Tasks (= 1.9.0)
  - Bolts-Swift (1.3.0)
  - Bolts/AppLinks (1.9.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.9.0)
  - FBSDKCoreKit (4.28.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.28.0):
    - FBSDKCoreKit
  - Parse (1.17.1):
    - Parse/Core (= 1.17.1)
  - Parse/Core (1.17.1):
    - Bolts/Tasks (~> 1.9)
  - Parse/FacebookUtils (1.17.1):
    - FBSDKCoreKit (~> 4.28.0)
    - FBSDKLoginKit (~> 4.28.0)
    - FBSDKShareKit (~> 4.28.0)
    - FBSDKTVOSKit (~> 4.28.0)
    - Parse/Core
  - Parse/TwitterUtils (1.17.1):
    - Parse/Core
  - Parse/UI (1.17.1):
    - Parse/Core
  - ParseLiveQuery (2.4.0):
    - Bolts-Swift (~> 1.3.0)
    - Parse (~> 1.17.0)
    - Starscream (~> 3.0.4)
  - Starscream (3.0.5)

**Comment by flovilmart** [comment]
Can you share a demo project to reproduce the issue as we are not able to reproduce it with the provided information. Please reopen the issue with the requested info.
