### ISSUE TITLE
Query doesn't return results

### ISSUE THREAD

**Issue by neilgandhi95** [parse-community/ParseLiveQuery-iOS-OSX#162]
Am I doing anything wrong here? 

   ```
let liveQueryClient: Client = ParseLiveQuery.Client(server: "ws://parseserver...com")
        
let msgQuery = PFQuery(className: "groups").whereKeyExists("name")
subscription = liveQueryClient.subscribe(msgQuery).handle(Event.created) { _, message in
      // This is where we handle the event
     print("WOW IT WORKS")
}
```

Thanks for the help!

**Comment by flovilmart** [comment]
do you retain the subscription somewhere? this should work. Did you follow the guides and other recommendations?

**Comment by vitor-ramos** [comment]
I'm having this issue too. When I use `Client.shared.shouldPrintWebSocketTrace = true`, I can see the message coming, but my handle function call is ignored.

**Comment by flovilmart** [comment]
Same question for you @vitor-Ramos, did you properly retain your subscription?

**Comment by vitor-ramos** [comment]
What do you mean by retain? This code is on my `viewDidLoad()`

**Comment by flovilmart** [comment]
Can you share your code?

**Comment by vitor-ramos** [comment]
```
func liveQuery () {
    Activity.registerSubclass()
    var activityQuery: PFQuery<Activity> {
        return (Activity.query()?
            .whereKey("locationId", equalTo: "kf3DWDrkpy9")
            .order(byAscending: "createdAt")) as! PFQuery<Activity>
    }
    let subscription: Subscription<Activity> = Client.shared.subscribe(activityQuery)
    subscription.handle(Event.created) { _, query in
        // Called whenever an object was created
        // NOT RECEIVING
        print("Print event received")
    }

    print("LiveQuery ViewDidLoad call function")
}
```

**Comment by thizzyDev** [comment]
Same issue here...

**Comment by flovilmart** [comment]
The subscription is not retained and it’s lifecycle is the one of the function, it’s destroyed before any event is emitted. You should keep the subscription as a class property to make sur it’s lifecycle is long enough.
