### ISSUE TITLE
The Swift pod `ParseLiveQuery` depends upon `Parse`, `Bolts` which do not define modules.

### ISSUE THREAD

**Issue by zackshapiro** [parse-community/ParseLiveQuery-iOS-OSX#163]
I've been trying to install ParseLiveQuery and debug its errors. I've included the error and my podfile below.

If I add `pod 'Parse/Core', '1.17.1', modular_headers: true` to replace the line, where I import `Parse/Core`, my project blows up with 14 warnings related to all kinds of FBSDK pods.

Surely people have installed this file in a combo objc/swift project. Any advice on how to fix?

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `ParseLiveQuery` depends upon `Parse`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

My Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
inhibit_all_warnings!

workspace 'wtbtest'

target 'wtbtest' do
    pod 'ROGoogleTranslate'
    pod 'Parse/Core', '1.17.1'
    pod 'Parse/FacebookUtils', '1.17.1'
    pod 'Bolts', '1.9.0', modular_headers: true
    pod 'Bolts-Swift', '1.4.0'
    pod 'JSQMessagesViewController', '7.3.3'
    pod 'FBSDKCoreKit', '~> 4.28.0'
    pod 'FBSDKShareKit', '~> 4.28.0'
    pod 'FBSDKLoginKit', '~> 4.28.0'
    pod 'ParseUI', '1.2.0'
    pod 'ParseLiveQuery', git: 'https://github.com/zackshapiro/ParseLiveQuery-iOS-OSX'
    pod 'FastttCamera', '0.3.4'
    pod 'SpinKit', '~> 1.1'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~>  3.8'
    pod 'BASSquareCropper', '~> 0.0'
    pod 'TOWebViewController', '~> 2.2.6'
    pod 'DGActivityIndicatorView', '2.1.1'
    pod 'HNKGooglePlacesAutocomplete', '~> 1.1'
    pod 'QBImagePickerController', '3.4.0'
    pod 'iCarousel', '~> 1.8'
    pod 'BLKFlexibleHeightBar', '1.0.2'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'SwipeView', '~> 1.3'
    pod 'FXBlurView', '~> 1.6'
    pod 'LXReorderableCollectionViewFlowLayout', '0.2.1'
    pod 'UIImageView-Letters', '1.1.4'
    pod 'NMRangeSlider', '~> 1.2'
    pod 'Transcontinental', '~> 1.0'
    pod 'CountryPicker', '~> 1.3'
    pod 'YLProgressBar', '~> 3.10.1'
    pod 'Mixpanel', '~> 3.3.0'
    pod 'Intercom', '5.0.0'
    pod 'MZTimerLabel', '0.5.4'
    pod 'Branch', '~> 0.24.2'
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'SlackTextViewController', '~> 1.9.6'
    pod 'Cartography', '~> 3.0.2'
    pod 'ReactiveSwift'
end
```

**Comment by flovilmart** [comment]
This is a case of mixing framwork targets and static lib targets. you should either `use_frameworks!` or use the https://github.com/flovilmart/cocoapods-mix-frameworks pods plugin.

Using the plugin require your to declare your framework dependencies against a framwork in your project (see the docs and demo project)

**Comment by zackshapiro** [comment]
Thanks for the fast reply @flovilmart. `use_frameworks!` seemed to solve my issues. Now I'm getting `file not found` for a different pod but at least no Facebook SDK errors.  I wonder if that new `file not found` is related to this?

**Comment by flovilmart** [comment]
`file not found` for which pod?

**Comment by zackshapiro** [comment]
[MBProgressHud](https://github.com/jdg/MBProgressHUD)

**Comment by flovilmart** [comment]
Do you have an example podfile / project to try out? This is odd, perhaps deleting the Pods folder and re-running `pod install` may help.

**Comment by zackshapiro** [comment]
I'll try adding this Podfile to a new project and seeing if I can recreate. If I can, I'll post the link for ya. The project I'm working with is a 2 year old Objc project that I've recently introduced Swift to. supported Swift version is 4.1

This is my now-updated Pods file

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
inhibit_all_warnings!
use_frameworks!

workspace 'wtbtest'

target 'wtbtest' do
    pod 'ROGoogleTranslate'
    pod 'Parse/Core', '1.17.1'
    pod 'Parse/FacebookUtils', '1.17.1'
    pod 'Bolts', '1.9.0'
    pod 'Bolts-Swift', '1.4.0'
    pod 'JSQMessagesViewController', '7.3.3'
    pod 'FBSDKCoreKit', '~> 4.28.0'
    pod 'FBSDKShareKit', '~> 4.28.0'
    pod 'FBSDKLoginKit', '~> 4.28.0'
    pod 'ParseUI', '1.2.0'
    pod 'ParseLiveQuery', git: 'https://github.com/zackshapiro/ParseLiveQuery-iOS-OSX'
    pod 'FastttCamera', '0.3.4'
    pod 'SpinKit', '~> 1.1'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Fabric', '~> 1.6'
    pod 'Crashlytics', '~>  3.8'
    pod 'BASSquareCropper', '~> 0.0'
    pod 'TOWebViewController', '~> 2.2.6'
    pod 'DGActivityIndicatorView', '2.1.1'
    pod 'HNKGooglePlacesAutocomplete', '~> 1.1'
    pod 'QBImagePickerController', '3.4.0'
    pod 'iCarousel', '~> 1.8'
    pod 'BLKFlexibleHeightBar', '1.0.2'
    pod 'HMSegmentedControl'
    pod 'SDWebImage', '~>3.8'
    pod 'SwipeView', '~> 1.3'
    pod 'FXBlurView', '~> 1.6'
    pod 'LXReorderableCollectionViewFlowLayout', '0.2.1'
    pod 'UIImageView-Letters', '1.1.4'
    pod 'NMRangeSlider', '~> 1.2'
    pod 'Transcontinental', '~> 1.0'
    pod 'CountryPicker', '~> 1.3'
    pod 'YLProgressBar', '~> 3.10.1'
    pod 'Mixpanel', '~> 3.3.0'
    pod 'Intercom', '5.0.0'
    pod 'MZTimerLabel', '0.5.4'
    pod 'Branch', '~> 0.24.2'
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'SlackTextViewController', '~> 1.9.6'
    pod 'Cartography', '~> 3.0.2'
    pod 'ReactiveSwift'
end
```

I also removed `Pods/` and `Podfile.lock` and did a reinstall but no luck

I get this error:

```
/Users/zackshapiro/dev/bump/wtbtest/wtbtest-Bridging-Header.h:10:9: note: in file included from /Users/zackshapiro/dev/bump/wtbtest/wtbtest-Bridging-Header.h:10:
#import "ForSaleListing.h"
        ^
/Users/zackshapiro/dev/bump/wtbtest/ForSaleListing.h:13:9: error: 'MBProgressHUD.h' file not found
#import "MBProgressHUD.h"
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/zackshapiro/Library/Developer/Xcode/DerivedData/wtbtest-ctuujvhczfwyyjaqqjksxjftahrk/Build/Intermediates.noindex/PrecompiledHeaders/wtbtest-Bridging-Header-swift_3KIRU5N6NS2WT-clang_1KK3V68N1TTM3.pch' for bridging header '/Users/zackshapiro/dev/bump/wtbtest/wtbtest-Bridging-Header.h'
```

**Comment by flovilmart** [comment]
Ah so that’s better, try removing the MBProgressHud.h import, double check the header search path :)

**Comment by zackshapiro** [comment]
What should the header search path be?

On Jul 31, 2018 at 7:14 PM, Florent Vilmart <notifications@github.com>
wrote:


Ah so that’s better, try removing the MBProgressHud.h import, double check
the header search path :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/163#issuecomment-409397841>,
or mute the thread

**Comment by flovilmart** [comment]
In the build settings, the header search path is usually managed by inherited from the pods project.

With a demo project I could very well help you, now, it’s quite tough. 

The file not found error means that at compile time, the header can’t be found. Can be because it was renamed or the search paths are wrong. 

Removing it from the bridging header may help you identigy what’s wrong (you may need to re add it everywhere it’s needed)

Also, because you’re using use_frameworks! You may wanna use `@import MBProgressHud`

**Comment by zackshapiro** [comment]
Grabbing dinner and then I’ll spin one up and send a link



On Jul 31, 2018 at 8:01 PM, Florent Vilmart <notifications@github.com>
wrote:


In the build settings, the header search path is usually managed by
inherited from the pods project.

With a demo project I could very well help you, now, it’s quite tough.

The file not found error means that at compile time, the header can’t be
found. Can be because it was renamed or the search paths are wrong.

Removing it from the bridging header may help you identigy what’s wrong
(you may need to re add it everywhere it’s needed)

Also, because you’re using use_frameworks! You may wanna use @import
MBProgressHud

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/163#issuecomment-409405725>,
or mute the thread

**Comment by zackshapiro** [comment]
@flovilmart Was able to recreate it here – https://github.com/zackshapiro/PodTest

Thanks for taking a look 🙌 

Removing the view controller `.h` file that includes `MBProgressHUD.h` from the bridging header allows the project to build. 🤔 

Seen this before?

**Comment by zackshapiro** [comment]
Looks like I had to import as `#import <MBProgressHud/MBProgressHud.h>` to avoid the error.

**Comment by flovilmart** [comment]
So it’s all good then? Using use_frameworks implies importing each framework instead of the single header file.

**Comment by zackshapiro** [comment]
@flovilmart yep, I got it all sorted. Thanks again for your help. Really appreciate it. Have a great one
