### ISSUE TITLE
Cannot convert value of type Subscription<PFObject> to specific type Subscription<GroupMessage>

### ISSUE THREAD

**Issue by zackshapiro** [parse-community/ParseLiveQuery-iOS-OSX#164]
Using version 2.4.0

In my AppDelegate I register GroupMessage as a subclass.

```
        let query = GroupMessage.query()!.whereKey("groupConvo", equalTo: groupConvo)
        let sub: Subscription<GroupMessage> = client.subscribe(query)

        sub.handle(Event.created) { query, message in
            print(message)
        }
```

However on the `let sub...` line, I get the error: Cannot convert value of type Subscription<PFObject> to specific type Subscription<GroupMessage>

Ideally I shouldn't have to cast `message` in the bottom closure to `GroupMessage` but right now it's a `PFObject` in that closure rather than it's subclass. I'm just following the readme at this point.

This is my GroupMessage object by the way

```final class GroupMessage: PFObject, PFSubclassing {

    static func parseClassName() -> String {
        return "GroupMessages"
    }

    var id: String {
        return objectId!
    }

    @NSManaged var groupConvo: GroupConvo
    var groupConvoId: String {
        return groupConvo.id
    }

    @NSManaged var senderId: String

    @NSManaged var text: String
}
```

Thanks

**Comment by flovilmart** [comment]
This is the query you should cast, not the subscription

**Comment by zackshapiro** [comment]
When I do: `let query:PFQuery<GroupMessage> = GroupMessage.query()!.whereKey("groupConvo", equalTo: groupConvo)`, it wants me to cast it as well. Shouldn't the generic function just take care of that by telling Swift what type the `let` is?

**Comment by flovilmart** [comment]
You need to cast to a `PFQuery<GroupMessage>`

**Comment by zackshapiro** [comment]
Got it. Thanks @flovilmart
