### ISSUE TITLE
SSL Handshake Failed when attempting to use wss and AWS

### ISSUE THREAD

**Issue by zackshapiro** [parse-community/ParseLiveQuery-iOS-OSX#166]
I've been working on getting my Parse Live Query working on my dev environment which is AWS + a classic load balancer.

Here is my load balancer setup
![](https://dzwonsemrish7.cloudfront.net/items/36451F3F0e2m1p0o1M0u/%5Baf6af55018851ed5be80a30ac3ff7ec9%5D_Screen+Shot+2018-08-13+at+5.15.23+PM.png)

In my view model I have the following code:

```
    private let client = ParseLiveQuery.Client(server: "wss://myApp-staging.us-east-1.elasticbeanstalk.com", applicationId: "userAppId", clientKey: "userClientId")
    var query: PFQuery<GroupMessage>? = nil
    var subscription: Subscription<GroupMessage>? = nil
```

In my `init` method, I do the following:

```
 self.query = GroupMessage.query()!.whereKey("groupConvoId", equalTo: groupConvo.id) as? PFQuery<GroupMessage>
        guard let query = query else { return }
        self.subscription = client.subscribe(query)

        subscription?.handle(Event.created) { _, message in
            if message.isSystemMessage {
                self.messages.insert(message, at: 0)
                self.delegate?.didReceiveNewGroupMessage(message)

                return
            }

            guard message.senderUserId != self.currentUserId else { return }

            self.messages.insert(message, at: 0)
            self.delegate?.didReceiveNewGroupMessage(message)
        }
```

Yet when I ultimately connect to the WebSocket, I get dozens of these errors, one after another (see below).

The SSL cert is valid. Been on the phone with AWS all day and based on one of their test projects internally with sockets, SSL and a classic load balancer, they recommended the load balancer setup in the image above.

```
2018-08-13 17:06:06.627772-0400 myApp[81125:15548610] CFNetwork SSLHandshake failed (-9807)
2018-08-13 17:06:06.627879-0400 myApp[81125:15548610] TCP Conn 0x6000014ba640 SSLHandshake failed (-9807)
2018-08-13 17:06:06.637697-0400 myApp[81125:15548747] ParseLiveQuery: WebSocket did disconnect with error: Optional(Error Domain=NSOSStatusErrorDomain Code=-9807 "(null)" UserInfo={_kCFStreamErrorCodeKey=-9807, _kCFStreamErrorDomainKey=3})
```

Throwing debuggers into my code, I see `public func reconnect()` is getting hit every time this error is thrown.

And the strangest part, when I post a message via the view controller, the data makes it to the dev server.

This is my `nginx.config`

```
files:
   /etc/nginx/conf.d/proxy.conf:
     owner: root
     group: root
     mode: "000644"
     content: |
       # Elastic Beanstalk Managed

       # Elastic Beanstalk managed configuration file
       # Some configuration of nginx can be by placing files in /etc/nginx/conf.d
       # using Configuration Files.
       # http://docs.amazonwebservices.com/elasticbeanstalk/latest/dg/customize-containers.html

       upstream nodejs {
           server 127.0.0.1:8081;
           keepalive 256;
       }

       server {
           listen 8080;

           if ($time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})T(\d{2})") {
               set $year $1;
               set $month $2;
               set $day $3;
               set $hour $4;
           }
           access_log /var/log/nginx/healthd/application.log.$year-$month-$day-$hour healthd;
           access_log  /var/log/nginx/access.log  main;

           location / {
               proxy_pass  http://nodejs;
               proxy_http_version 1.1;
               proxy_set_header        Upgrade $http_upgrade;
               proxy_set_header        Connection "upgrade";
               proxy_set_header        Host            $host;
               proxy_set_header        X-Real-IP       $remote_addr;
               proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
           }

       gzip on;
       gzip_comp_level 4;
       gzip_types text/html text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

       }

   /opt/elasticbeanstalk/hooks/configdeploy/post/99_kill_default_nginx.sh:
     owner: root
     group: root
     mode: "000755"
     content: |
       #!/bin/bash -xe
       rm -f /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf
       service nginx stop
       service nginx start

container_commands:
  removeconfig:
    command: "rm -f /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf /etc/nginx/conf.d/00_elastic_beanstalk_proxy.conf"
```

Any help would be hugely appreciated. Thanks!

**Comment by flovilmart** [comment]
Have you considered posting on server fault or stackoverflow as this seems to be a regular websocket + https + AWS elastic beanstalk issue.

Did you try with a regular websocket client? The JS SDK client?

**Comment by zackshapiro** [comment]
I haven't. But I will. Good idea.

I haven't tried with another WebSocket client yet either, only this library. it works fine with `ws://` but not `wss://`.

**Comment by flovilmart** [comment]
Yeah, that points to an invalid certificate errors what’s the real endpoint of your app? You can mail it directly if you wish to keep it (admin@parseplatform.org)

**Comment by zackshapiro** [comment]
Will email now

**Comment by zackshapiro** [comment]
For anyone who comes across this in the future, here's what was going wrong.

I have an Alias via AWS's Route 53 to point `dev.myApp.com` at the url `myApp-staging.us-east-1.elasticbeanstalk.com`. 

The SSL cert was for `*.myApp.com`, so doing this:

`private let client = ParseLiveQuery.Client(server: "wss://myApp-staging.us-east-1.elasticbeanstalk.com", applicationId: "userAppId", clientKey: "userClientId")` 

was connecting to the wrong URL without a proper cert, going around AWS's infrastructure.

I hope this can help someone out in the future.

And an eternal thank you to @flovilmart for all of the help and fast community support he does around here!
