### ISSUE TITLE
Issue getting updates via subscription 

### ISSUE THREAD

**Issue by zackshapiro** [parse-community/ParseLiveQuery-iOS-OSX#167]
I have an object called a `GroupConvoMeta` and this object has an array of strings on it called `memberIds`. I'm trying to set up a subscription to track when its updated so that I can inspect the `memberIds` and see who has entered or left the group. 

None of my subscription closures are being called. I've added the name of the class, "GroupConvoMeta" to my array of live query-able. I'm not sure what's going wrong here. Would love another set of eyes.

In my view controller, at the top of the VC, I have

```
private var client: ParseLiveQuery.Client? = nil

var metaQuery: PFQuery<GroupConvoMeta>? = nil
var metaSubscription: Subscription<GroupConvoMeta>? = nil
```

and in the `init`, I have

```
self.client = ParseLiveQuery.Client()

self.metaQuery = GroupConvoMeta.query()!.whereKey("groupConvoId", equalTo: groupConvo.id) as? PFQuery<GroupConvoMeta>
        guard let metaQuery = metaQuery else { return }
self.metaSubscription = client?.subscribe(metaQuery)
```

Below that in `init`, I also have

```
        metaSubscription?.handle(Event.entered) { query, meta in
            print("entered")
            

        }

        metaSubscription?.handle(Event.updated) { query, meta in
            print(bar)
            print(meta)
         }      
```

I'm able to track `created` events for other classes but not `entered` or `updated` 

Thanks!

**Comment by flovilmart** [comment]
@zackshapiro I understand you found the solution on your own, can you perhaps ellaborate for s/o who may encounter the same?

**Comment by zackshapiro** [comment]
As I typed this out, I realized that I hadn't added the class to my live query class names in my index.js. Once I did that and deployed I was all good!

Still got some docs to write for ya @flovilmart once I get this feature out! Haven't forgotten about you

**Comment by flovilmart** [comment]
Hahaha :) glad to hear!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
