### ISSUE TITLE
Bolts-Swift 1.4.0

### ISSUE THREAD

**Issue by ranhsd** [parse-community/ParseLiveQuery-iOS-OSX#169]
Hi, I noticed that the live query Podspec depends on Bolts 1.3.0  

![image](https://user-images.githubusercontent.com/3685671/45816529-8f725400-bce4-11e8-90b2-ee582bc8301f.png)

Bolts-Swift latest release is 1.4.0 and when I try to specify the specific Bolts-Swift version in my Podfile I get the following error: 

![image](https://user-images.githubusercontent.com/3685671/45816559-ad3fb900-bce4-11e8-9fe0-ed0db5853873.png)

There is a reason why live query not depends on the latest Bolts-Swift release? 

Thanks in advance.

**Comment by flovilmart** [comment]
Because no one opened a PR to support it.

**Comment by ranhsd** [comment]
Hi @flovilmart I will change the version in the podspec. It will take me some time to test that everything is ok in my app and then I will submit the PR

**Comment by jumper4000** [comment]
Hi, is this fixed yet? I'm having the same issue. For some reason, Bolts-Swift 1.3 won't compile anymore (it used to), and I can't download version 1.4 because of LiveQuery dependancy.
