### ISSUE TITLE
Using Bolts 1.4

### ISSUE THREAD

**Issue by JoseVigil** [parse-community/ParseLiveQuery-iOS-OSX#170]
Installed xcode 10 and running on swift 4

I need to update to Bolts-Swift 1.4.0 but LiveQuery is only running in 1.3.0 or else I get an error on Task.swift https://github.com/BoltsFramework/Bolts-Swift/issues/63

Is there a workaround until the upgrade? 

Edit: This patch seems to skip the issue, not sure if solve it
https://github.com/BoltsFramework/Bolts-Swift/issues/63#issuecomment-367091489

Now its a question of upgrade only. Within the roadmap?

Thanks lot
Jose

**Comment by flovilmart** [comment]
Feel free to open a Pr with the fix when you have it!

**Comment by JoseVigil** [comment]
Hi Flo,

I was able to run with xcode 10.1 beta 2 and swift 4

`pod 'Parse'
pod 'Bolts-Swift', :git => 'https://github.com/BoltsFramework/Bolts-Swift', :commit => 'e9baa72d04521c3b25ef4fa6fef12b340953ee02'
pod 'ParseLiveQuery'`

Side effect is randomly having a linked command failed error. 

> Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_BFTaskCompletionSource", referenced from:
      objc-class-ref in BoltsHelpers.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Solution once and then remove ParseLiveQuery folder into DeriveData - Products and everything goes well.

Thanks

**Comment by flovilmart** [comment]
Do you want to open a PR for it?

**Comment by noobs2ninjas** [comment]
I am closing this as the current version of ParseLiveQuery supports Bolts-Swift 1.4.0
