### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by flovilmart** [parse-community/ParseLiveQuery-iOS-OSX#172]
Due to recent events I won’t be able to provided effective maintenance of both the iOS SDK and LiveQuery SDK’s. 

If any one wants to jump in, let me know here and we’ll organize a smooth transition.

**Comment by noobs2ninjas** [comment]
I'd be interested in this @flovilmart. I use Parse Live Query all the time.

**Comment by acinader** [comment]
Hi @noobs2ninjas.  Yes, we'd love help with this repository.

you could start by running through the open issues and the open pull request and suggesting what we ought to do with them.  How's that sound?

**Comment by noobs2ninjas** [comment]
Sounds perfect! Thanks @acinader !
