### ISSUE TITLE
CocoaPods install doesn't compile

### ISSUE THREAD

**Issue by drdaz** [parse-community/ParseLiveQuery-iOS-OSX#174]
I've made an example Xcode project (no code from me) where the Podfile is as follows:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'PodsTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodsTest
  pod 'Parse'
  pod 'ParseLiveQuery'

  target 'PodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodsTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Running pod install creates a workspace which doesn't compile. It looks like the version of Bolts-Swift (1.3.0) linked to doesn't compile. 

<img width="419" alt="screenshot 2018-10-31 at 14 26 49" src="https://user-images.githubusercontent.com/845731/47791059-0d307300-dd19-11e8-8bc2-7d395a541b71.png">

The code actually looks wrong to me:

<img width="666" alt="screenshot 2018-10-31 at 14 28 56" src="https://user-images.githubusercontent.com/845731/47791155-4ec11e00-dd19-11e8-9ba5-4de41056943d.png">

I've tried forcing Bolts-Swift 1.4.0 into the mix by specifying so in the Podfile. Running pod update in this config yields a version 1.4.0 of the Parse iOS SDK and 2.2.3 of ParseLiveQuery. But the project compiles.

This doesn't seem quite right.

**Comment by drdaz** [comment]
[PodsTest.zip](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/files/2534577/PodsTest.zip)

Here's the reproducer.

**Comment by drdaz** [comment]
Running a local repo with the current code, and bumping the Bolts-Swift dependency to 1.4.0 builds fine.

I haven't done any other testing yet.

**Comment by drdaz** [comment]
Here's a PR with the Podspec bump needed to fix this https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/175

**Comment by TomWFox** [comment]
@drdaz Can this be closed now?

**Comment by drdaz** [comment]
@Tom-Fox1 I just updated to the current release in the project I use this in. It builds fine now. :)

Closing.
