### ISSUE TITLE
LiveQuery Question...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/ParseLiveQuery-iOS-OSX#176]
Hello,

I have implemented Parse Server and Parse Live Query and it appears that Parse LiveQuery is firing every other time I make a change int the DB.  For example, I have a bool value field in the collection.  If I change it I get the event, if I change it back I don't get the event and then if I change it again I get the event.  I am changing the fields using the Parse Dashboard.

The events are firing every other time.  This happens with any field I change.

Is this a known issue?  

I just wanted to rule that out before I get to deep into trying to figure out what is going on.  Or if anyone has heard of this, maybe I am doing something wrong in my implementation.

Thanks for any insight.

**Comment by ShawnBaek** [comment]
Could you shows your code in here?

It is my subscribe function

```swift
func handleEvent(event: Event<Post>) {
        if Thread.current != Thread.main {
            return DispatchQueue.main.async { [weak self] in
                self?.handleEvent(event: event)
            }
        }
        switch event {
        case .created(let obj),
             .entered(let obj):
             print("Object is entered!")
        case .updated(let obj):
             print("Object is updated!")
        case .deleted(let obj),
             .left(let obj):
             print("Object is deleted!")
        }
    }
}

```

**Comment by TomWFox** [comment]
What type of subscription are you using?

**Comment by noobs2ninjas** [comment]
Since we never got a response I'll assume this issue is closed.
