### ISSUE TITLE
Can't find initWithServer with 2.5.0 and objc

### ISSUE THREAD

**Issue by junya100** [parse-community/ParseLiveQuery-iOS-OSX#181]
When I update LiveQuery client version to 2.5.0, our build fail by missing initWithServer method from objc code.
This following obj-c code can't be compiled.
[[PFLiveQueryClient alloc] initWithServer:liveQueryServer applicationId:@"XXX" clientKey:nil];

**Comment by johnsonejezie** [comment]
I have this issue too. added @objc to the public init as temporary solution so I can continue development.

**Comment by junya100** [comment]
I made PR. https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/184

**Comment by laramarie** [comment]
What's the status here? I also need this fix.

**Comment by TomWFox** [comment]
#184 has been merged now, so I’ll close this.
