### ISSUE TITLE
OSX - Unidentified Developer and bundle format is ambiguous (could be app or framework)

### ISSUE THREAD

**Issue by guidupas** [parse-community/ParseLiveQuery-iOS-OSX#187]
I am trying to Archive an App for Distribution using Developer ID to run on Mac OSX.

It builds fine and finishes all the processes, but when I try to run the App it shows me an `Unidentified Developer` Message.

I tried to use `--deep` signing in `Other code signing flags` and, when it comes to the `ParseLiveQuery Framework`, it returns a `bundle format is ambiguous (could be app or framework)` error during the building process.

<img width="761" alt="Captura de Tela 2019-05-13 às 23 37 57" src="https://user-images.githubusercontent.com/12818273/57669496-2a53d180-75d9-11e9-9e7f-18a61b63e1ec.png">

**Comment by guidupas** [comment]
I have solved this problem deleting the `ParseLiveQuery.framework`, rebuilding it using Carthage and recompiling the App changing the App version and build.

**Comment by noobs2ninjas** [comment]
Glad you got it worked out.
