### ISSUE TITLE
Callbacks not called due to garbage collection

### ISSUE THREAD

**Issue by rostopira** [parse-community/ParseLiveQuery-iOS-OSX#190]
I've installed this via CocoaPods, but build fails with following error:
```
Header 'BoltsSwift-Swift.h' not found
```
![image](https://user-images.githubusercontent.com/16724952/58956608-6842b080-87a7-11e9-9384-c9e205499369.png)

P.S.: I use Xcode 10.2

**Comment by rostopira** [comment]
Solved using
```
    pod 'ParseLiveQuery'
    pod 'Bolts-Swift', :git => 'https://github.com/bpisano-luna/Bolts-Swift.git'
```
That's strange

**Comment by rostopira** [comment]
I can clearly see correct messages from and to websocket, but callbacks never called, what the heck

**Comment by rostopira** [comment]
`weak var` Should be included in the docs.

**Comment by noobs2ninjas** [comment]
@rostopira I am actually started working on getting this project up to speed from many previous unreleased commits. I experienced the same thing you did and it caused me hours of trial and error and I could only get the delegate sorry "Subscription Handling" protocol to work. Where did you find weak var? Thats doesn't makes much sense when you're dealing with asynchronous tasks that passes a closure expression. Nothing during this process has any business being declared weak.

**Comment by rostopira** [comment]
@noobs2ninjas See this commit in my fork: https://github.com/rostopira/ParseLiveQuery-iOS-OSX/commit/24730207733a88d84a03dd293b24196ef2ac9055

And `weak` is still here: https://github.com/parse-community/ParseLiveQuery-iOS-OSX/blob/master/Sources/ParseLiveQuery/Internal/ClientPrivate.swift#L36

**Comment by rostopira** [comment]
@noobs2ninjas also, weak could make sense, if it were properly documented and actually cancels subscription, but it's not the case

**Comment by noobs2ninjas** [comment]
Even with documentation the place where it completely falls apart every time is when accessing the client via singleton as you can simply pass in closures eliminating the need to make a reference to anything.

**Comment by rostopira** [comment]
@noobs2ninjas so, if you agree with me, just remove `weak`, what's the problem?

**Comment by noobs2ninjas** [comment]
I do. Just pointing out that it probably should be removed either way. Would you mind updating this issues title and doing a commit from your branch to resolve this issue?  I'm looking to do a release soon and would love to get this in there and give you credit for the fix.

**Comment by rostopira** [comment]
NP, I will do
