### ISSUE TITLE
ParseLiveQuery 1.0.1 Issues

### ISSUE THREAD

**Issue by khawarb** [parse-community/ParseLiveQuery-iOS-OSX#192]
Whenever i try to install ParseLiveQuery by using below pod command
pod 'ParseLiveQuery'
It install 1.0.1 version, How i can install latest version 2.5.0. Simple Parse version is 1.13.0 and it's also not updating to its latest version.

**Comment by noobs2ninjas** [comment]
@khawarb did you ever figure this out? If so let me know and I'll get you some info.

**Comment by noobs2ninjas** [comment]
This actually isnt an issue with parse live query. I just fired up a new project and PLQ 1.6.1 installed just fine. It sounds actually like the cached version cocoapods has on file. Try running pod update to get the latest headers and tell me if this fixes it. 

Oh! another potential issue could be the minimum version of iOS you are supporting. Cocoapods also takes your minimum target and picks the latest version of each pod that supports it. I think our minimum version is iOS 8 currently.

**Comment by TomWFox** [comment]
Closing due to lack of response and this also doesn't seem to be an issue with this repo. Please reopen if the problem persists.
