### ISSUE TITLE
Updating ParseLiveQuery Travis configurations for Xcode 10.2 or 11

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/ParseLiveQuery-iOS-OSX#194]
I have a pull request updating ParseLiveQuery to use Swift 5. Upon submitting a pull request I noticed that Jenkins wasn't building and needed a few configuration updates. I changed settings to what I thought would work but I am getting this error in the logs. 

> ERROR | [iOS] unknown: Encountered an unknown error (Could not find a ios simulator (valid values: com.apple.coresimulator.simruntime.ios-10-0 

It continues to list all simulator values but this should get the point across. I have no idea what I need to do. I noticed in Parse that they have a Rakefile that has the following.

`namespace :test do
  desc 'Run iOS Tests'
  task :ios do |_, args|
    task = XCTask::BuildTask.new do |t|
      t.directory = script_folder
      t.workspace = 'Parse.xcworkspace'

      t.scheme = 'Parse-iOS'
      t.sdk = 'iphonesimulator'
      t.destinations = ["\"platform=iOS Simulator,OS=12.2,name=iPhone X\"",]
      t.configuration = 'Debug'
      t.additional_options = { "GCC_INSTRUMENT_PROGRAM_FLOW_ARCS" => "YES",
                               "GCC_GENERATE_TEST_COVERAGE_FILES" => "YES" }

      t.actions = [XCTask::BuildAction::TEST]
      t.formatter = XCTask::BuildFormatter::XCPRETTY
    end
    unless task.execute
      puts 'iOS Tests Failed!'
      exit(1)
    end
`
This seems to follow the documentation for Travis. However in ParseLiveQuery we have this in our config.yml in the .circleci folder. 

> `- run: xcodebuild build -workspace ParseLiveQuery.xcworkspace -sdk iphonesimulator -scheme ParseLiveQuery-iOS -configuration Debug -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c;

I'm sure this is practically the same thing but I feel like bringing ParseLiveQuery files more in line with the Parse .yml and script files that this would be a bit easier to maintain when we have Xcode, Swift, and iOS/Mac OS version bumps. Either way though I still dont know quite where the issue is. If someone could take a look and give me a hand I'd appreciate it. You can find my pull request [here](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/193).

**Comment by TomWFox** [comment]
There are issues with the circle CI build as well... not sure how to fix yet.

**Comment by noobs2ninjas** [comment]
I think what I'd like to try is setting the structure much like what you did with Parse @TomWFox. Its very cut and dry and I think it would be easier to maintain. What do you think? If you agree I'll remove my pull request and fork and create a new fork and just for this update and I'll message here when I have a pull request up so you can look it over.

**Comment by TomWFox** [comment]
Absolutely, go ahead!

**Comment by TomWFox** [comment]
Guessing we can close this now?

**Comment by noobs2ninjas** [comment]
Technically not yet. Not until parse can build with our bolts branch and our release build passes here.

**Comment by drdaz** [comment]
Sorry, but why is this not done? This library now builds using Xcode 11.2.1. All the automated tests look like they're passing.

If there's something going on with the main SDK, surely that's something that should be described and dealt with in an issue there. 

There's one place that this project imports Bolts directly (BoltsHelpers.swift), and that usage doesn't look like it would be affected by our changes. In fact, it doesn't look like that method (objCTask(task)) is used anywhere.

If there's something I'm missing, by all means fill me in, but as is I'm having trouble understanding what's actually missing for this issue to be closed 🙂.

**Comment by noobs2ninjas** [comment]
@drdaz sorry this is done. I thought this was from the parse repo.
