### ISSUE TITLE
Handler and Event Handler and much deeper issues.

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/ParseLiveQuery-iOS-OSX#196]
Last night I was about at the end of my wits with ParseLiveQuery. After getting several errors from the server and being forced to include a where statement in my query. I then followed the documentation exactly as well as the dozen other handler functions many of which seem to overlap. After a few hours of tinkering not a single handler was called. Then I decided to have my class adopt the `SubscriptionHandling` protocol and set myself as the handler set it as the handler when subscribing and **BOOM** everything works. 

Now I've been slowly watching ParseLiveQuery decay over the last few years and be maintained less and less. Now we are at a point where 75% of all callback methods never get called. To make matters worse it has as dependencies that are all being poorly maintained as well Bolts, Bolts Swift, StarScream. The entire project is bloated and dependencies and are inconsistent to the point where nothing compiles. The moment you try to update it at all the circleCI and travis files fall apart and wont build anymore. I know it's semantics but things like `SubscriptionHandling` is very poorly named and doesn't follow Apples development best practices for naming conventions. I know its just semantics but If I hadn't gone and read the source code myself I would have had no clue it it basically was just a poorly named delegate. *Breath*

So, heres what I am really thinking. A part of me wishes we could gut this thing and just make it a module of the main Parse library like ParseUI. That would at least guarantee that after bringing it up to Parse standards that it will stay that way. It also would make test file maintenance and target compatibility more consistent. However, I think a good start would be to go in there and strip everything down and just get it to a place that works. Theres 'SubscriptionHandling' eventHandlers, handlers, etc. Theres 100 different ideas going too many directions all to accomplish the same exact initialization, subscription as well as ways to get your response. Thats too much, none of its documented, and most of it doesn't work. So, I propose we strip it down till we have a nice finely tuned, easy to understand, and consistent as well as easy to maintained library. 

Sorry for the rant. I just really am a bit disappointed that one of my favorite libraries has gotten so bad and I'm tired of working on the iOS docs which needs even more help haha. Im open for ideas.

**Comment by TomWFox** [comment]
I'm sorry to hear that your experience has been so frustrating. I don't personally have any experience with live query but I will do my best to review / get someone to review any PRs you submit.

I totally agree that it would be much better if live query was a submodule of the main iOS SDK although I would also say that at this point that is the least of our problems...

> iOS docs which needs even more help

I would have to dispute that! I've put quite a bit of work into keeping the iOS docs up to scratch, but I know they're not perfect - we'll get there!

**Comment by noobs2ninjas** [comment]
Sorry @TomWFox I was a bit strong. You are right, and a true hero for all you do for Parse. Seriously.  I can actually tell what you've worked on and what hasn't been touched in a while. So don't think it doesn't show. I was super irritated with PLQ after hours of working on docs and then when I have actual client work to do PLQ is stopping me dead in my tracks. The reason I'm wanting to help out is because I'm up there with the best of em in terms of reaping the the rewards of Parse specifically for iOS. 

So back to the topic. I need PLQ to work. I don't want to step on any toes so let me just ask you this. Is there anyone actively working on PLQ right now? If I'm going to focus on getting PLQ working and decluttering the project a bit. I'll close my swift 5 pull request and just work in Swift 4 and getting this building in Travis and and Circle.  After we get to that point I'd like to work on bringing it over as a Module. I figure the easiest way to do that though is to start with an individual library that works well.

**Comment by TomWFox** [comment]
As far as I'm aware there is no one actively working on the iOS live query repo. There has been the odd contribution but noting major so you certainly won't be stepping on any toes!

Your plans make sense to me, it will be great to see this repo in a better state!
