### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/ParseLiveQuery-iOS-OSX#198]
We need a new branch created called "Release 2.6.0" with the 2.6.0 tag and then merged or a new release manually created. @flovilmart or @TomWFox  or whoever has the ability we need to get this released and we need someone who can do this do this in the future. I so want to get this thing moving again.

**Comment by noobs2ninjas** [comment]
Finally figured out how to do releases so that Jenkins would try to deploy the release. We got all the way through it and...

> Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.

I don't know if either you @flovilmart or @TomWFox have access but all I think needs to be done is to generate a new trunk token and add it to Jenkins. Not sure if theres any other info like email that has to match in the test files but the issue should be something like that.

**Comment by TomWFox** [comment]
I’ll take a look at the Jenkins token, I should be able to generate a new one.

I didn’t realise but you already have write access to this repo.

**Comment by TomWFox** [comment]
So I've added my GitHub token to travis. The trunk token may take a little longer, I've contacted @flovilmart about adding a new owner.

**Comment by TomWFox** [comment]
I’ve got ownership of the pod now so I should be able to generate a new token, I’ll let you know when I’ve added a new token to travis.

**Comment by TomWFox** [comment]
So I've added a new token now, rerun the travis build and a new version has been successfully published to cocoapods.
