### ISSUE TITLE
Livequery drops connection while using in swift5

### ISSUE THREAD

**Issue by ahsanghauri** [parse-community/ParseLiveQuery-iOS-OSX#207]
Hello I am facing a issue where live query doesn't trigger live events some time while connection is established with parse server.

**Comment by noobs2ninjas** [comment]
@ahsanghauri I think moving to swift 5 and experiencing new issues is just a coincidence with an underlying issue we had and should be fixed with 1.6.1. could you verify that you are using version 1.6.1?

**Comment by ahsanghauri** [comment]
thanks I just updated the version and now the issue is resolved
