### ISSUE TITLE
iOS and iPad OS 13 Updates

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/ParseLiveQuery-iOS-OSX#209]
Apple is officially allowing submission of iOS and iPad OS 13 applications. I wanted to start a issue to start getting the ball rolling as this is going to require:

- iPad OS target be added
- Test/Deploy XCode version be updated for CircleCI/Travis
- New Build Target added to test files.

Being that the official iOS/ iPad OS release date coming on September 30th we might want to start moving.

**Comment by noobs2ninjas** [comment]
@TomWFox or @dplewis could I get one of you to open a branch to start working on this aka 2.7.0 ?

**Comment by TomWFox** [comment]
I'm sure you should be able to create new branches, you have write permission on this repo.

**Comment by TomWFox** [comment]
I've created a `working-2.7.0` branch anyway.

**Comment by noobs2ninjas** [comment]
Weird. I thought I had a button on github itself. Didnt see one. I could have assumed incorrectly and was just too lazy to try via terminal.

**Comment by TomWFox** [comment]
<img width="1054" alt="Screenshot 2019-09-14 at 23 21 56" src="https://user-images.githubusercontent.com/13188249/64914264-7dd05a80-d746-11e9-8a8f-4da1b88541ba.png">

**Comment by noobs2ninjas** [comment]
OHHH! I was going into the "Branches" page and looking for a  New Branch button just like you go Issues and click "New Issue" or go into Pull Requests and click "New Pull Request". I've used github forever and I always thought that was just a Searchbar. Haha now that I think about it. Have I never used the site to add a branch before? weird.

**Comment by TomWFox** [comment]
It could definitely be more clear!
