### ISSUE TITLE
Is Unsubscribing and Resubscribing From Live Query Bad For The Server?

### ISSUE THREAD

**Issue by danielchangsoojones** [parse-community/ParseLiveQuery-iOS-OSX#213]
I have an iOS app where every time I enter the home screen, I subscribe to 2 live queries.
Then, when I leave the home screen, I unsubscribe from the 2 live queries. Users can go back and forth between the home screen and other screens, so the users are subscribing and unsubscribing many times (maybe 50+ times) to the live query. Is that bad for server memory or cpu usage? I'm only unsubscribing the subscriptions, should I be disconnecting and reconnecting the liveQueryClient also?

**Comment by davimacedo** [comment]
I think it is fine in terms of server load. I'd leave the connection open as well.
