### ISSUE TITLE
PFPointerObjectEncoder error caused app to crash in Release 2.6.1 

### ISSUE THREAD

**Issue by bayareahank** [parse-community/ParseLiveQuery-iOS-OSX#215]
Run into a PFPointerObject encoding error, for pointer to PFObject, in release 2.6.1. It caused the app to crash each time liveQuery starts subscription. This is pretty consistent, and easily reproducible. The error msg is like following: 

[PFPointerObjectEncoder encodeObject:]: unrecognized selector sent to instance

It reports error in QueryEncoder.swift, in line dealing with encoding of PFObject Pointer.  Line number 49 (for release 2.6.1's version of QueryEncoder.swift). 

else if let object = val as? PFObject {
                encodedQueryDictionary[key] = (try? PFPointerObjectEncoder.object().encode(object)) as? Value
}

Looks encoding with PFPointer is passed with wrong selector. 

This is relatively new, Parse query works fine with PFObject pointer, just liveQuery crashed. I verified that liveQuery with pointer to PFObject works with 2.5.0. Code looks runs fine with 2.6.0 also. I noticed QueryEncoder.swift was changed after 2.6.1 was released, not sure whether that will fix this. 

Sample code to trigger this bug, try making a liveQuery with any pointer to PFObject in its predicate.

let message = Message(text: "Hello", source: "you", target: "me")
chatQuery = PFQuery(className: "Message")
            .whereKey("target", equalTo: message.pfObject)
// Message being a simple PFObject wrapper, with getter/setter from a PFObject it wraps around. 

Replace object with built in types, like String comparison, it will run fine.

**Comment by bayareahank** [comment]
BTW, @TomWFox  @noobs2ninjas, I don't know CircleCI or Travis. See #206 .   Bootstrapping a startup now, I wish I could do more to help with the code. 

Thanks for the good work, please keep up.

**Comment by noobs2ninjas** [comment]
What happens when you just run the query aka does it only break when using it in ParseLiveQuery?

Also, I could be completely wrong here but if I thought doing `.whereKey("key", equalTo: object)` is the same as doing `.whereKey("objectId", equalTo: "s2k4n5n")`. If that is that case then your object doesnt have an objectId. Try to just run your query and see what happens, and if that works I'll go have a look.

**Comment by noobs2ninjas** [comment]
Looking at the differences between 2.6 and 2.6.1 [here](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/compare/2.6.0...2.6.1) I see that the majority of our changes was bumping parse versions. I am assuming this is where the changes occurred. I actually have a pull request out right now that updates the Parse version again to the latest. I'm still working on getting it out as it also updates our build to Xcode 11. Anyway, when 2.7.0 comes out lets look at this again and see if that fixes it. 

Also, you might check and see what version of Parse you are running in your project.

**Comment by bayareahank** [comment]
Good pointer. 

Yet it looks the bug is triggered even before it talks with the server on live query subscription. I triggered this bug on ParseServer 3.4.4, I tried the latest 3.9.0, it is still there. FYI.

**Comment by bayareahank** [comment]
Don't observe this any more. Closing it.
