### ISSUE TITLE
Subscription handler failing on array of subscriptions

### ISSUE THREAD

**Issue by brianmwadime** [parse-community/ParseLiveQuery-iOS-OSX#219]
Hello,
I am try to create multiple subscriptions and adding them to an array, but the handlers don't seem to get fired when the objects and created/updated.

But it works fine with a single subscription. Is it not possible to have an array and have all the subscription handlers fire as well?

```swift
 threads?.forEach({[weak self] (thread) in
        guard let me = self else { return }
        let msgQuery = PFMessage.query()
        msgQuery?.whereKey("threadId", equalTo: thread.objectId)
        me.subscriptions?.append(subscription!)
        me.subscriptions?.last?.handle(Event.created) { _, message in
          if let messsage = Message(message: message) {
            if(messsage.senderId == userId) { return }
            messsage.post()
          }
        }
  })
```

**Comment by brianmwadime** [comment]
nvm, figured out a solution, everything works when I keep an array of the handlers.

**Comment by noobs2ninjas** [comment]
@brianmwadime what version are you running? It should not be dropping the handler references. The current version had a fix for this, or so we thought.

**Comment by brianmwadime** [comment]
@noobs2ninjas I did an update and they started working. The fix is solid.

**Comment by noobs2ninjas** [comment]
@brianmwadime Just wanted to make sure. Thanks for letting me know.
