### ISSUE TITLE
Change query for subscription?

### ISSUE THREAD

**Issue by joshuaTTL** [parse-community/ParseLiveQuery-iOS-OSX#220]
Hey guys, 

I'm developing a group chat app with live query and it works pretty well. However, I'm having trouble knowing how I can change the query for subscription when the user, say, creates a new group, in which case the orQuery should be  add one more condition. 

The are two ways I have been thinking of: 
1. Disconnect and the reconnect with the new conditions
2. Manage multiple subscriptions at the same time.

However, neither sounds to be a safe and effective solution. 

Any help is appreciated!!!

**Comment by cbaker6** [comment]
It seems you should unsubscribe and resubscribe to the updated query.
