### ISSUE TITLE
 ParseLiveQuery: WebSocket did disconnect with error: nil

### ISSUE THREAD

**Issue by samirmagnates** [parse-community/ParseLiveQuery-iOS-OSX#225]
I am creating a chat app using live query, and I have a server of NodeChef, every time when I am subscribing my live query its subscribe successfully and then give error :

 ParseLiveQuery: WebSocket did disconnect with error: nil

My code is working fine in back4app.com and same code is not working on NodeChef server.
My code:

      `      
        let predicate = NSPredicate(format: "conversation_id == %@", conversationId)
        self.conversation_query = Messages.query(with: predicate)?.order(byAscending: "createdAt")
        
        self.conversation_query.findObjectsInBackground { (objects, err) in
            if err==nil {
                if let messages = objects as? [Messages] {
                    self.messages = messages
                    self.collectionView.reloadData()
                }
            }
        }
        
        self.subscriber = Client(server: Parse.currentConfiguration!.server)
        self.subscriber.shouldPrintWebSocketTrace = true
        self.subscriber.shouldPrintWebSocketLog = true
        self.subscription = subscriber.subscribe(conversation_query)
        
        
        if (self.subscription != nil) {
            print("subscription done successfully");
        }
        else {
            print("something is wrong in subscription");
        }
        
        self.subscription.handle(Event.created, { (query, object) in
            print("Item created In Live Query Table")
            if let message = object as? Messages {
                self.messages.append(message)
                DispatchQueue.main.async {
                    self.finishReceivingMessage(animated: true)
                }
            }
        })
`

     `Log of my app code 
        subscription done successfully
        2020-04-06 19:49:08.449143+0530 ParseChat[7759:305805] didMoveToWindow
        2020-04-06 19:49:11.301765+0530 ParseChat[7759:306041] ParseLiveQuery: WebSocket did disconnect with error: nil
        2020-04-06 19:49:15.464242+0530 ParseChat[7759:306031] ParseLiveQuery: WebSocket did disconnect with error: nil
      `

**Comment by noobs2ninjas** [comment]
Sounds like the actual ParseServer need some configuration. Thats the most common reason for that error. I'll see if I can try it myself and check to see which versions of Bolts, Parse Server etc... they are using. One thing you have to remember is that since Parse is open source, many services do customizations that after a while stop working with the current version of parse. 

One thing I'd tell you is that we are going to see a new version of Bolts and Parse very soon anyway. So, why don't I check this out with the hosts and then we'll update to the new version and try again when that comes out.

**Comment by samirmagnates** [comment]
hi @noobs2ninjas , 

Thanks for your feedback, could you please tell me when we get updated new version?

**Comment by TomWFox** [comment]
Hopefully within the next few days. For both Live Query and the main SDK we are just waiting for a new Bolts release to be published to cocoapods.

**Comment by davidolesch** [comment]
@samirmagnates did you resolve this issue?

**Comment by cbaker6** [comment]
If this is still an issue, feel free to reopen and update the issue.
