### ISSUE TITLE
Issue with nested PFQuery in a OR query

### ISSUE THREAD

**Issue by jlott1** [parse-community/ParseLiveQuery-iOS-OSX#227]
I was having issues with a more complex OR query that had a nested matches query.  
I believe this relates to the issue [#156](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/156)

           let activityGroupQuery = PFQuery(className: Activity.getModelName())
            let groupMatchQuery = PFQuery(className: Group.getModelName())
            groupMatchQuery.whereKey("objectId", containedIn: groups.getGroupIds())
            activityGroupQuery.whereKey("groups", matchesQuery: groupMatchQuery)
            
            let activityOwnerQuery = PFQuery(className: Activity.getModelName())
            activityOwnerQuery.whereKey("ownerId", equalTo: userId)
            let orQuery = PFQuery.orQuery(withSubqueries: [activityGroupQuery, activityOwnerQuery])
            
            subscription = client?.subscribe(orQuery)

          
I have made a fix [here](https://github.com/jlott1/ParseLiveQuery-iOS-OSX/commit/6b8034accadee957e983df4c53b648e473363722) that seems to be working.  
I wanted to post this issue so that others would know about it.  this is my first time posting an issue and first time committing a change.  Apologies if I didn't follow proper procedures.  I was kind of in a hurry.

**Comment by cbaker6** [comment]
Can you create a pull request from your branch with the fix?
