### ISSUE TITLE
Multiple subscriptions adds additional sends after socket opens?

### ISSUE THREAD

**Issue by noobs2ninjas** [parse-community/ParseLiveQuery-iOS-OSX#23]
I just tested how many times things are getting sent to the server by printing every time the sendOperationAsync function gets called like so.

```
func sendOperationAsync(operation: ClientOperation) -> Task<Void> {
        return Task(.Queue(queue)) {
            let jsonEncoded = operation.JSONObjectRepresentation
            let jsonData = try NSJSONSerialization.dataWithJSONObject(jsonEncoded, options: NSJSONWritingOptions(rawValue: 0))
            let jsonString = String(data: jsonData, encoding: NSUTF8StringEncoding)
            print("socket is sending jsonString")
            self.socket?.send(jsonString)
        }
    }
```

I am subscribing to 2 queries back-to-back and after the socket connects I am seeing 3 "socket is sending jsonString" printed. Does this mean that I am getting subscribed twice to one of my subscriptions?

**Comment by nlutsenko** [comment]
Not necessarily.
Any chance you can print out the `jsonString` by itself (in a form of a UTF8 string of course).
What I would expect is `connect (in a form of json) -> subscription1 -> subscription2`.

**Comment by Eke** [comment]
I think one is for connect and two are for subscribe

**Comment by nlutsenko** [comment]
@Eke Awesome to have you here! :grin:

**Comment by Eke** [comment]
@nlutsenko  thanks :smile_cat:

**Comment by noobs2ninjas** [comment]
Drp! Haha not sure why I didnt think of that. You are right. One is for the connect itself with the sessionToken.
