### ISSUE TITLE
Could not build Objective-C module 'ParseLiveQuery'

### ISSUE THREAD

**Issue by abeticlairon** [parse-community/ParseLiveQuery-iOS-OSX#232]
Unable to build ParseLiveQuery in Xcode 12

**Comment by julianvogels** [comment]
The current Cocoapods release 2.7.1 is not compatible with iOS14 / Xcode 12 yet. 

You have to either wait for version 2.7.2 to be added to Cocoapods by the maintainer of this repository, or work around the issue by changing the Pod definition in your Podfile to
```
pod 'ParseLiveQuery', :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX', :branch => 'master'
```
The contents of the master branch can change unexpectedly though, so be sure to change it to 
```
pod 'ParseLiveQuery', '2.7.2'
```
as soon as it is released to Cocoapods.

**Comment by abeticlairon** [comment]
Thank you @julianvogels 
Unfortunately, 2.7.2 is not yet available via Cocoapods. I get the error `[!] CocoaPods could not find compatible versions for pod "ParseLiveQuery":
  In Podfile:
    ParseLiveQuery (= 2.7.2)`

**Comment by vexelgray** [comment]
@abeticlairon you can add this line in your podfile to install 2.7.2 version

`pod 'ParseLiveQuery', :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX.git', :commit => '57d2b01'`

Using xCode12 i can't build the project in obj-c, there are several errors 

Regards,

**Comment by TomWFox** [comment]
2.7.2 is out on cocoapods now.
