### ISSUE TITLE
ParseLiveQuery v2.7.2 not pushed into Cocoapods

### ISSUE THREAD

**Issue by JoeSzymanski** [parse-community/ParseLiveQuery-iOS-OSX#233]
ParseLiveQuery v2.7.2 has not been pushes into the Cocoapods spec repo, so it's not accessible as a dependency in podspec files.

We are blocked on updating both ParseLiveQuery and Parse in our frameworks because of this.

**Comment by TomWFox** [comment]
<img width="361" alt="Screenshot 2020-10-06 at 17 59 47" src="https://user-images.githubusercontent.com/13188249/95235646-c51c0400-07fd-11eb-8415-8fed81657dd4.png">
