### ISSUE TITLE
Client.swift Errors, Won't Compile

### ISSUE THREAD

**Issue by talkaboutdesign** [parse-community/ParseLiveQuery-iOS-OSX#24]
Here is the error message I get when trying to build project: 

<img width="384" alt="screen shot 2016-04-05 at 3 08 30 pm" src="https://cloud.githubusercontent.com/assets/2926534/14294693/55640eec-fb40-11e5-8ab0-11861516bd13.png">

**Comment by Eke** [comment]
are you using latest version?

**Comment by otymartin** [comment]
@talkaboutdesign Update to latest parse server

**Comment by talkaboutdesign** [comment]
What does latest server have to do with Framework not compiling in Xcode.

**Comment by talkaboutdesign** [comment]
Here is my pod file

```
use_frameworks!

target 'ParseLive' do
pod 'ParseLiveQuery'
pod 'Parse'
end
```

**Comment by nlutsenko** [comment]
Try running `pod update`, if it doesn't help - could you paste the output here?

**Comment by Eke** [comment]
@talkaboutdesign this bug was in firs version release and they fixed it. see #2 issue

**Comment by talkaboutdesign** [comment]
pod update helped. Seems to be a bug then when starting new project. Downloads older version by default.

**Comment by nlutsenko** [comment]
:) Glad it helped.
