### ISSUE TITLE
Podfile update needed

### ISSUE THREAD

**Issue by kmaker** [parse-community/ParseLiveQuery-iOS-OSX#244]
I'm using ParseLiveQuery pod (https://cocoapods.org/pods/ParseLiveQuery) which currently depends on Parse 1.19.0.
Parse 1.19.0 has compilation issues on Xcode 12.3, which they had fixed on 1.19.1.
Could you update the ParseLiveQuery pod so it depends on this new version of Parse?

**Comment by cbaker6** [comment]
You should be able to resolve this in your pod file without a release as ParseLiveQuery can use `~>1.19.0`, per the [Pod spec](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/blob/da22df1da3c44bdae357c03a5d3a52e3f502ae0c/ParseLiveQuery.podspec#L26). Just add

```
pod 'Parse', '1.19.1'
```

to your Podfile

**Comment by kmaker** [comment]
Perfect. Thanks!
