### ISSUE TITLE
Please add SPM Support

### ISSUE THREAD

**Issue by owais-applligent** [parse-community/ParseLiveQuery-iOS-OSX#254]
Installing through CocoaPods is old way... Please add support to the Swift package manager for better support.

**Comment by bayareahank** [comment]
Up this. I used Carthage and it gave me all kinds of headache, each time after XCode major update.

**Comment by proj-sashido** [comment]
Another vote for Swift Package Manager support!

**Comment by mtrezza** [comment]
I think we should combine this repository with the main repository, which already has SPM support; https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues/262.

**Comment by mtrezza** [comment]
Closing, as LiveQuery has been added as a module to the [Parse Apple SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1714#issuecomment-1588711321) and is now available via SPM.
