### ISSUE TITLE
Include of non modular

### ISSUE THREAD

**Issue by Sofianebenabdallah** [parse-community/ParseLiveQuery-iOS-OSX#26]
I would like to try it. I create a podfile with : 

pod 'ParseLiveQuery'

I have this error when I try to build it :
<img width="895" alt="capture d ecran 2016-04-07 a 21 55 24" src="https://cloud.githubusercontent.com/assets/17195768/14364961/9e40633c-fd0b-11e5-9031-f16aae421093.png">

Thank you for you help

**Comment by Eke** [comment]
If you have project in objective-c add `use_frameworks!` to your pod file at start. 

But after this you will need to change `#import` to `@import`

**Comment by Sofianebenabdallah** [comment]
Hi,

I work in Swift. I use this command, because without I had this error in pod 

`[!] Pods written in Swift can only be integrated as frameworks; add`use_frameworks!`to your Podfile or target to opt into using it. The Swift Pods being used are: Bolts-Swift and ParseLiveQuery
`

**Comment by Eke** [comment]
@Sofianebenabdallah  try to clean Xcode's DerivedData, remove Pods folder, run `pod install`

**Comment by Sofianebenabdallah** [comment]
Still not good :(

**Comment by nlutsenko** [comment]
Change of #import to @import - unrequited, if modules are enabled and working it's all the same (using latter improves performance, but only in a very minor way.

@Sofianebenabdallah, which version of CocoaPods are you using? 0.39 or 1.0.0 beta?
Also, trying completely removing `Pods` folder and re-running `pod install`.

**Comment by Sofianebenabdallah** [comment]
Hi,

I have 0.39. Must I install 1.0 beta?

Sofiane

**Comment by nlutsenko** [comment]
You don't have to, no, but I would recommend trying?

**Comment by Sofianebenabdallah** [comment]
💯  Right. Every thing works well with 1.0.0 beta 6 

thank you !!

**Comment by nlutsenko** [comment]
Perfect! Glad it worked!
