### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by arg2u** [parse-community/ParseLiveQuery-iOS-OSX#27]
After install ParseLiveQuery with cocoapods. I have error in BoltsHelper.swift - could not build objc module "Bolts" and another one error  "Include of non-modular header inside framework module 'Bolts.BFCancellationToken'

**Comment by Eke** [comment]
see #26

**Comment by arg2u** [comment]
ok when i install new cocoa pods i have new error -  could not build objc module "Parse"

**Comment by chadpav** [comment]
I just went through this. Installed Cocoapods 1.0 rc1 resolved it for me.  Which version of cocoa pods did you install?  

Are you getting more than one error?
