### ISSUE TITLE
includeKey(s) not working?

### ISSUE THREAD

**Issue by wosheesh** [parse-community/ParseLiveQuery-iOS-OSX#30]
When querying and using includeKey or includeKeys for Pointer-types, the referred objects are not loaded. Is this working as intended in ParseLiveQuery or am I doing something wrong?

Query declaration:

```
    var messagesQuery: PFQuery {
        return (Message.query()?
            .whereKey("roomId", equalTo: currentChatRoom!.objectId!)
            .includeKeys(["author", "room"])
            .orderByAscending("createdAt"))!
```

Subscription:

```
    subscription = liveQueryClient
        .subscribe(messagesQuery)
        .handle(Event.Created) { _, message in
            print("message author.objectId : \(message.author.objectId)")
        }
```

The last line produces error:
`[__NSCFDictionary objectId]: unrecognized selector sent to instance`

**Comment by CiraciNicolo** [comment]
Is author an 'Object' type on Parse? If so, the error is correct.

**Comment by wosheesh** [comment]
It is a PFObject. Why is the error correct? In another place in my code I have a similar query not handled by LiveQuery, also pointing to a user Object and same call results without error.

**Comment by wosheesh** [comment]
Is this because Pointers are not yet supported? #31 #16

**Comment by xissburg** [comment]
Pointers are not yet supported? Then what's the point?

**Comment by xissburg** [comment]
I thought I could work around it in a way... but nor the current session, nor ACLs are supported. This is still extremely limited and not very useful.

**Comment by AmbroiseCollon** [comment]
I have encountered the same issue. Live query without pointers is really limited. Any schedule on this ? How can we help ? What about includeKeys ? Thanks

**Comment by agordeev** [comment]
I'm having the same problem. Here's more info: https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/issues/40

**Comment by AmbroiseCollon** [comment]
Any timeline on this ? How can we contribute ? Thanks !

**Comment by agordeev** [comment]
The problem is LiveQuery returns `NSDictionary` instead of `PFObject`.

**Comment by peuf0u** [comment]
Any progress on this issue ? I've noticed that the object encoding/decoding is fixed so LiveQuery is returning PFObject. However you don't receive the full object even though the query contains includeKey.

**Comment by flovilmart** [comment]
@Patrez this is a server side issue, the includeKey is ignored when subscribing to the query. The decision tree is processed synchronously after an object is saved on parse-server, therefore we don't have the opportunity to inject inclusions. We'd need to refactor the whole serverside logic in order to support those.

**Comment by peuf0u** [comment]
Oh I understand and do you think that parse-server will support includeKey and LiveQueries? Should I create an issue on parse-server?

**Comment by flovilmart** [comment]
Pull requests are welcome, if this is a feature of interest, we may start the refactor that may enable more powerful live queries. Note that this will have a negative impact performance, forcing a 'read' on the DB after each save that matches the query. It was designed to not have such impact. Do you want to tackle that in a pull request?

**Comment by rafaelmaroxa** [comment]
Definitely interested in this.

**Comment by hatimmakki** [comment]
Is there a solution for this?
