### ISSUE TITLE
App crashes when subscribe to a query with Pointer constraints

### ISSUE THREAD

**Issue by cetorres** [parse-community/ParseLiveQuery-iOS-OSX#31]
I'm trying subscribe to a query that has a Pointer constraint (e.g. query.equalTo('user', Parse.User.current()))), but the app is crashing when tries to subscribe. The query is perfect because I tested with query.findObjectsInBackgroundWithBlock and runs and bring results.
Maybe internally it's not handling the Pointer correctly yet, accessing its objectId to be able to filter que query.

**Comment by ghost** [comment]
I think Pointers are not yet supported, that's why in Swift example room doubled by roomName and author by authorName. The best way for now is to store with user his objectId, e.g. userId in subscription class.

**Comment by Eke** [comment]
Pointers are not supported yet. see issue #16
