### ISSUE TITLE
Add carthage support.

### ISSUE THREAD

**Issue by CiraciNicolo** [parse-community/ParseLiveQuery-iOS-OSX#32]
No description needed.

**Comment by nlutsenko** [comment]
Unfortunately, we are blocked by SocketRocket here, since we depend on it and it doesn't have support for Carthage.
This said, I am going to try out adding it there, so every benefits from this.

**Comment by DazChong** [comment]
+1, Or releases `.framework`
I dislike pod added so much stuff in my project.

**Comment by ghost** [comment]
+1

**Comment by willysharp5** [comment]
Any updates on Carthage Support

**Comment by flovilmart** [comment]
The latest version should work with Carthage

**Comment by flovilmart** [comment]
@willysharp5 that should work now, the 1.1.0 release was uploaded with the .framework for iOS and OSX.

**Comment by willysharp5** [comment]
How do I run it. It's not documented on the wiki page.

**Comment by flovilmart** [comment]
Like any other Carthage framework.

Add:

github "parseplatform/ParseLiveQuery-iOS-OSX"

To your Cartfile

**Comment by willysharp5** [comment]
I tried github "ParsePlatform/ParseLiveQuery-iOS-OSX" and it worked. Maybe this should be documented in the readme page
Thanks for adding this @flovilmart

**Comment by willysharp5** [comment]
Is there a way to make it work with swift 2.3 ?

ld: Carthage/Build/iOS/BoltsSwift.framework/BoltsSwift compiled with newer version of Swift language (3.0) than previous files (2.0) for architecture x86_64

**Comment by flovilmart** [comment]
No, like stated in the changelog, the master branch is on 3.0. There is no plan to support 2.3 on a separate branch.

**Comment by willysharp5** [comment]
I missed that in the Changelog. Thanks
