### ISSUE TITLE
Best practice to use the data in a tableview from the LiveQuery

### ISSUE THREAD

**Issue by FredvanRijswijk** [parse-community/ParseLiveQuery-iOS-OSX#38]
Because it's really new and documentation is not available, making our own documentation. I receive the data and I have tried many ways to add this data to a tableview with 

```
import UIKit
import Parse
import ParseLiveQuery

let liveQueryClient = ParseLiveQuery.Client()

class TestLiveQuery: UIViewController {

 var messageObjects = [PFObject]()

private var subscription: Subscription<Message>?

var myQuery: PFQuery {
    return (Message.query()?
        .whereKey("roomName", equalTo: "test")
        .orderByAscending("createdAt"))!
}

override func viewDidLoad() {
    super.viewDidLoad()


    let username = "Tes"
    let password = "testtest"

    PFUser.logInWithUsernameInBackground(username, password: password).continueWithBlock { task in
        return nil
    }

    self.printPriorMessages()
    self.subscribeToUpdates()

}




@IBAction func sendMessageButton(sender: AnyObject) {

    let message = Message()
    message.author = PFUser.currentUser()
    message.authorName = message.author?.username
    message.message = "Hello: \(NSDate().toShortTimeString())"
    message.room = PFObject(withoutDataWithClassName: "Room", objectId: "rzCQzJbRzF")
    message.roomName = "test"
    message.saveInBackground()

}

func printPriorMessages() {
    myQuery.findObjectsInBackground().continueWithBlock() { task in
        (task.result as? [Message])?.forEach(self.printMessage)
        return nil
    }
}

func subscribeToUpdates() {
    subscription = liveQueryClient
        .subscribe(myQuery)
        .handle(Event.Created) { _, message in
            self.printMessage(message)
    }
}

private func printMessage(message: Message) {
    let createdAt = message.createdAt ?? NSDate()
    print("\(createdAt) \(message.authorName ?? "unknown"): \(message.message ?? "")")
}
}

extension NSDate {

func toShortTimeString() -> String {
    let formatter = NSDateFormatter()
    formatter.timeStyle = .ShortStyle
    let timeString = formatter.stringFromDate(self)

    return timeString
}
} 
```

by doing this 

```
func printPriorMessages() {
    myQuery.findObjectsInBackground().continueWithBlock() { task in
        (task.result as? [Message])?.forEach(self.printMessage)
        print("printPrioMessages")
        self.tableView.reloadData()
        return nil
    }
}

func subscribeToUpdates() {
    subscription = liveQueryClient
        .subscribe(myQuery)
        .handle(Event.Created) { _, message in
            self.printMessage(message)
            print("subscribe updates")
            self.messageObjects.append(message)


            let insertionIndexPath = NSIndexPath(forRow: self.messageObjects.count - 1, inSection: 0)
            self.tableView.insertRowsAtIndexPaths([insertionIndexPath], withRowAnimation: .Automatic)

            print(self.messageObjects.count)


    }
}

private func printMessage(message: Message) {
    let createdAt = message.createdAt ?? NSDate()
    //print("printMessage")
    self.messageObjects.append(message)
    print("\(createdAt) \(message.authorName ?? "unknown"): \(message.message ?? "")")
}
```

But it's getting messy and crashing etc... So if somebody has a working example, I want to load the data in a tableview and if it's getting new data insert a row with the new data in the tableview.

**Comment by AmbroiseCollon** [comment]
Here is [what i came up with](https://gist.github.com/AmbroiseCollon/af54f8514cdbae1a49bc72b769d64580). I'd be really happy to hear your suggestions.

**Comment by FredvanRijswijk** [comment]
@AmbroiseCollon 

I get a problem with this: 

Cannot invoke value of type '(Event<PFObject>) -> ()' with argument list '(Event<PFObject>)' on self.games.updateWithEvent(event) 

Want to test it, but can't fix this problem

**Comment by AmbroiseCollon** [comment]
Try using a subclass of PFObject and use that Subclass instead of PFObject in `LiveQueryArray.swift` file ?

This works for me.

```
import Foundation
import Parse
import ParseLiveQuery

extension _ArrayType where Generator.Element == PFObject {
    mutating func updateWithEvent(event: Event<Game>) { // <= Game is a PFObject Subclass
        switch event {
        case .Created(let object):
            append(object)
        case .Entered(let object):
            append(object)
        case .Deleted(let object):
             if let index = indexOf(object) {
                removeAtIndex(index)
            }
        case .Left(let object):
            if let index = indexOf(object) {
                removeAtIndex(index)
            }
        case .Updated(let object):
            if let index = indexOf(object) {
                self[index] = object
            }
        }
    }
}
```

**Comment by FredvanRijswijk** [comment]
@AmbroiseCollon 

`import Foundation
import UIKit
import Parse
import ParseUI
import ParseLiveQuery

let liveQueryClient = ParseLiveQuery.Client()

class TableViewController: PFQueryTableViewController {
    // MARK: - Properties
    var messages = [PFObject]() {
        didSet {
            print("didset")
            tableView.reloadData()
        }
    }
    var myQuery: PFQuery? {
        return Message.query()?
            .whereKey("roomName", equalTo: "test")
            .orderByAscending("createdAt")
    }
    
    private var subscription: Subscription<Message>?
    
    // MARK: - Methods
    override func viewDidLoad() {
        super.viewDidLoad()
        self.load()
        //self.subscribeToUpdates()
        
        
    }
    
    /**
     Load games from DB
     */
    func load() {
        myQuery?.findObjectsInBackgroundWithBlock({ (objects, error) in
            if error == nil {
                if let objects = objects {
                    self.messages = objects
                    self.subscribeToUpdates()
                    print("subscribe updates load")
                    
                }
            } else {
                print("error : \(error?.userInfo)")
            }
        })
    }
    
    /**
     Check for any update and modify games property accordingly
     */
    
    
    func subscribeToUpdates() {

            subscription = liveQueryClient
                .subscribe(myQuery!)
                .handleEvent { _, event in
                    self.messages.updateWithEvent(event)
                    print("subscribe updates")
            }
        }
 

    @IBAction func addObjectButton(sender: AnyObject) {
        
        
        let message = Message()

        message.message = "Hello: \(NSDate().toShortTimeString())"
        message.roomName = "test"
        message.saveInBackground()
        
        
    }

    
    // Classic table view logic continues with games as data source
    
    override func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        //Return the number of sections
        return 1
    }
    
    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // Return the number of rows in the section
        return objects!.count
    }
    
    
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath, object: PFObject!) -> PFTableViewCell? {
        
        let cell: PFTableViewCell! = tableView.dequeueReusableCellWithIdentifier("cellChat", forIndexPath: indexPath) as? PFTableViewCell
        
        cell.textLabel?.text = (object.objectForKey("message") as! String)
        
        
        return cell
    }
    

    
}

extension NSDate {
    
    func toShortTimeString() -> String {
        let formatter = NSDateFormatter()
        formatter.timeStyle = .MediumStyle
        let timeString = formatter.stringFromDate(self)
        
        return timeString
    }
}
`

and 

`
import Foundation
import Parse
import ParseLiveQuery

extension _ArrayType where Generator.Element == PFObject {
    mutating func updateWithEvent(event: Event<Message>) { // <= Game is a PFObject Subclass
        switch event {
        case .Created(let object):
            append(object)
        case .Entered(let object):
            append(object)
        case .Deleted(let object):
            if let index = indexOf(object) {
                removeAtIndex(index)
            }
        case .Left(let object):
            if let index = indexOf(object) {
                removeAtIndex(index)
            }
        case .Updated(let object):
            if let index = indexOf(object) {
                self[index] = object
            }
        }
    }
}`

this is the subclass

`import Foundation
import Parse

class Message: PFObject, PFSubclassing {

    @NSManaged var message: String?
    @NSManaged var roomName: String?

    class func parseClassName() -> String {
        return "Message"
    }
}`

don't know if it's subscribed or not and when / how they tableview is updating or not

**Comment by ShawnBaek** [comment]
@AmbroiseCollon in Swift 3 is not working could you update snippet code?

**Comment by flovilmart** [comment]
Try that: https://github.com/flovilmart/cocoaheads-mtl-parse-server/blob/master/ios/CocoaHeaders/LiveTableViewController.swift
