### ISSUE TITLE
Live Queries iOS docs don't exist

### ISSUE THREAD

**Issue by otymartin** [parse-community/ParseLiveQuery-iOS-OSX#4]
https://parse.com/docs/ios/guide#live-queries

**Comment by nlutsenko** [comment]
The docs are coming very soon! @richardjrossiii, can you help out with that?

**Comment by otymartin** [comment]
@nlutsenko Thanks @richardjrossiii Make sure to nail the server side  implementation side for the noobs :)

**Comment by otymartin** [comment]
@nlutsenko @richardjrossiii Hey is this being published anytime soon? Really struggling with implementation without documentation.

Thanks

**Comment by Eke** [comment]
@otymartin what kind of problems do you have? maybe i can help you

**Comment by otymartin** [comment]
Accidentally closed the issue hehe @Eke thanks for offer of help.

Basically, I'm lost as to how utilize liveQueries vs. the old queries (Maybe syntax is throwing me off swell because swift docs aren't out yet so I'm following javascript docs (I don't know javascript well)
Let me use an example.

Right now for my chatrooms in my message apps, I the "Message" class were all messages are dropped

``` swift
 let messageQuery = PFQuery(className: "Message")
//I THEN FIND OBJECTS
   messageQuery.findObjectsInBackgroundWithBlock { (results: [PFObject]?, error:NSError?) -> Void in {
//THEN APPEND THE NEW TEXT INTO THE CHATROOM
let messages = results
self.messages.append(chatMessage)
}
```

Following the javascript docs, this is a `create event` happening.
The subscription syntax then is

``` javascript
subscription.on('update', (object) => {
  console.log('object updated');
});
```

How do I translate this to swift so I can subscribe to new messages created in my chatroom and push them to the chat window in realtime?

I had opened the issue in #13

**Comment by vyachesIavskiy** [comment]
Link is not working
