### ISSUE TITLE
Subscribe without params not work?

### ISSUE THREAD

**Issue by arg2u** [parse-community/ParseLiveQuery-iOS-OSX#41]
I create query without params where and want to subcribe. But handle error: "
Error: ServerReportedError(code: 1, error: "Missing required property: where", reconnect: true)"

**Comment by richardjrossiii** [comment]
This seems like a backend bug, I'd suggest reporting it over at [ParsePlatform/parse-server](https://github.com/ParsePlatform/parse-server).

Feel free to reopen this issue if you can find any client-side issues with registering a query without a clause (there shouldn't be).

**Comment by tsanthosh** [comment]
From the parse live query protocol:

> The query.where field is mandatory. It represents the condition of the ParseQuery the client subscribes to. The format of the where field is the same with ParseQuery's REST API format. You can check the detail here. Right now we support $lt, $lte, $gt, $gte, $ne, $in, $nin, $exists, $all, $regex, $nearSphere, $within and normal equal condition. Any unsupported conditions will be ignored.
