### ISSUE TITLE
include of non-modular header inside framework module 'Bolts BFCancellationToken' 

### ISSUE THREAD

**Issue by Samigos** [parse-community/ParseLiveQuery-iOS-OSX#44]
Hey everyone...

I just downloaded the Parse sample project, installed LiveQueries pod and nothing else. When I try to build it, it pops the two errors below.. What's wrong?

I'm using Xcode 7.3.1
![screenshot at 17 22-14-31](https://cloud.githubusercontent.com/assets/9467442/16161990/161be0ca-34d9-11e6-8656-aee006720e90.png)

**Comment by Samigos** [comment]
Any idea guys?

**Comment by vikdenic** [comment]
I am having the same exact issue. Did you ever find a solution for this, @Samigos? -Thanks

**Comment by Samigos** [comment]
@vikdenic Unfortunately no... No one seems to know why it's happening...

**Comment by gfosco** [comment]
cc @nlutsenko

**Comment by AssemSherief** [comment]
I was able to solve this by updating the cocoapods installation using the terminal command:

`sudo gem install cocoa pods`

Then updated my pod file to look like that:

```
use_frameworks!
target "TargetName" do
    pod 'ParseLiveQuery'
end
```

Then performed a `pod install` to update everything

**Comment by Samigos** [comment]
I tried it but the problem still remains..

**Comment by Samigos** [comment]
I did that and now I'm facing the below errors:
![screenshot at 29 18-55-02](https://cloud.githubusercontent.com/assets/9467442/17254633/3c587a68-55be-11e6-8acd-7a7c2acbb384.png)

**Comment by milguad** [comment]
Replace the lines with the following:
Line 36 Replace with:
 taskCompletionSource.trySet(error: error)
Line 38 replace with: 
taskCompletionSource.trySet(result: result)

**Comment by Samigos** [comment]
@milguad Thanks! That removed the errors..

**Comment by vikdenic** [comment]
I am still getting this error and have tried all above solutions.

The podfile looks identical to the one @AssemSherief posted. And the Pod target is set to allow non-modular headers.

I am on Xcode 8 beta 6
