### ISSUE TITLE
Can not find subscriptions under this class XXXX

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [parse-community/ParseLiveQuery-iOS-OSX#48]
In my app didFinishLaunchingWithOptions function  
`var userQuery: PFQuery {
            return (users.query()?.whereKey("name", equalTo: "ABC"))!
        }`

```
   ` let liveQueryClient = ParseLiveQuery.Client()
    liveQueryClient
        .subscribe(userQuery)
        .handle(Event.Created) { _, user in
            print(user)
    }`
```

My PFQuery works if I use userQuery.findObjectsInBackground.
but nothing  happens when I add a new row into the table.
I checked the error log in dashboard it says "Can not find subscriptions under this class users" whenever I add a new row.
 How can I make the live query work?

**Comment by FelipeCardoso89** [comment]
👍

**Comment by tkunstek** [comment]
When you started the parse server, did you add it to the list of subscriptions. Most people do this in index.js:

  liveQuery: {
    classNames: ["User", "Chat"] // List of classes to support for query subscriptions
  },

**Comment by Samigos** [comment]
If you tried @tkunstek suggestion and the problem still remains, it means you aren't declaring the Subscription correctly in your client... Try the following approach:

```
var subscription: Subscription<PFObject>?
var userQuery: PFQuery { return (users.query()?.whereKey("name", equalTo: "ABC"))! }

subscription = userQuery.subscribe()
subscription!.handle(Event.Created) { (_, user) in
    print(user)
}
```

Hope it works!
