### ISSUE TITLE
File BoltsHelpers.swift is not updated on cocoapods and is still not compatible with new swift.

### ISSUE THREAD

**Issue by klemenzagar91** [parse-community/ParseLiveQuery-iOS-OSX#54]
<img width="1123" alt="screen shot 2016-08-02 at 09 43 47" src="https://cloud.githubusercontent.com/assets/5512848/17320804/aa137506-5895-11e6-9f30-4d329dda3b4c.png">

This is the error that I get. I user ParseLiveQuery v1.0.1

**Comment by agordeev** [comment]
I'm getting the same error. Looks like BoltsHelpers file isn't compatible with new version of Bolts. @nlutsenko can you please check this?

**Comment by mitrenegade** [comment]
👍 i get the same error. simple fix is to replace those methods with trySet(error: error) and trySet(result: result) but of course it would be great to update the pod specs. Thanks!
