### ISSUE TITLE
ParseLiveQuery ObjC

### ISSUE THREAD

**Issue by milguad** [parse-community/ParseLiveQuery-iOS-OSX#55]
Since there is little info available about live query in ObjC, I'm trying to understand the concept by doing trial and error. So far, I have managed to include the ParseLiveQuery 1.0.1 in my project (not without overcoming a few issues first). 

Now, I am testing the code and see how the callback works. Therefore I have the following method:

`

```
-(void) liveQuerytest {
__weak typeof(self) weakSelf = self;

//Init the Client
//self.client = [[PFLiveQueryClient alloc] init];
self.client = [[PFLiveQueryClient alloc] initWithServer:PARSE_SERVER
                                          applicationId:PARSE_APPLICATION_ID
                                              clientKey:PARSE_CLIENT_KEY];

PFQuery *OnlineQ = [PFQuery queryWithClassName:@"TestingClass"];

[OnlineQ whereKey:@"objectId" equalTo:@"TR9nmpKp8"];

[OnlineQ orderByAscending:@"createdAt"];

//NSLog(@"This is the query: %@", [OnlineQ findObjectsInBackground]);

[OnlineQ findObjectsInBackgroundWithBlock:^(NSArray * _Nullable objects, NSError * _Nullable error) {
    if (!error) {

        NSLog(@"The objects: %@", objects); 
        weakSelf.subscription = [[weakSelf.client subscribeToQuery:OnlineQ] addCreateHandler:^(PFQuery * query, PFObject * obj) {
            NSLog(@"The object that has changed: %@ %@",obj.createdAt, obj.objectId);
        }];

        NSLog(@"the subscription status: %@", self.subscription);

    }
}];
  }
```

`

Now the query works fine and I received the objects as it suppose to. For testing purpose, I am updating the class with the following cURL: 

`curl -X PUT \ 
   -H "X-Parse-Application-Id: XXXXXXXXXXXXXXXXXXXX" \
   -H "X-Parse-MASTER-Key: XXXXXXXXXXXXXXXXX" \
   -H "X-Parse-Url: http://localhost:1337/parse" \
   -H "Content-Type: application/json" \
    -d  '{"testing":"other test is done"}' \
    http://localhost:1337/parse/classes/TestingClass/TR9nmpKp8`

The update is done properly, but I dont see any changes in the client in the subscription. It is the correct way to go about this and why the callback is not working. 

Thanks for any info that you can bring to solve this issue.

**Comment by Neilfau** [comment]
Any luck with this?

**Comment by ljs19923** [comment]
How did you succeed in installing this Swift library in your Objc project with Cocoapodes ... I did not get there

**Comment by flovilmart** [comment]
>  but I dont see any changes in the client in the subscription

you're using the `addCreateHandler` which will fire when a new object is created and matches the query you're subscribed to.

You should use the [`addUpdateHandler`](https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/blob/master/Sources/ParseLiveQuery/ObjCCompat.swift#L215) to be notified of an object that's being updated.
