### ISSUE TITLE
Is the Parse Live Query ideal to use for chatting/messaging applications?

### ISSUE THREAD

**Issue by taufiq-husain** [parse-community/ParseLiveQuery-iOS-OSX#6]
I'm using Heroku as a server but I'm wondering if it's a good idea to create real-time chatting/messaging applications using the Live Query feature too?

**Comment by otymartin** [comment]
@taufiq-husain I would like an answer to this too. Off the top of my head it should work because the logic is no different from push notifications except its better faster and more reliable. So in my chat app that I'm building, Im thinking, I should be able to subscribe to any messages that man be created or updated within an existing chat room and it should update in realtime just like imessenger or something. I'm waiting for the iOS documentation so I can figure out the server side - That's the only place I get suck is the server side implementation.

**Comment by Eke** [comment]
@taufiq-husain  @otymartin i think there will be no problem to implement real-time chatting/messaging :) something similar is implemented in demo

**Comment by nlutsenko** [comment]
Yup, it would work just great for realtime chat/messaging. Our demo app is indeed a sample of how you would build a simple chat room based messaging app.

Realtime Queries work the same way as usual queries, but the changes are delivered almost instantly, meaning real time. For example, if you have a messages query for a specific room or person - every new message is going to be pushed to your device and you'll know in an instant that there is a new message, so you can update the UI accordingly.

Hope this helps and answers your question, guys. Let me know if there is anything else.

**Comment by otymartin** [comment]
@nlutsenko 
Hey right now I have an implementation where a method is triggered by a push notification coming from an external device.

eg.
`func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {
        NSNotificationCenter.defaultCenter().postNotificationName("launchIncomingChat", object: nil)
        NSNotificationCenter.defaultCenter().postNotificationName("reloadMessages", object: nil)
    }`

What would the implementation look like using liveQueries?

**Comment by nlutsenko** [comment]
You would need to construct a query on the client, then it would something along the lines of:

``` swift
let query = PFQuery(className: "Message")
query.subscribe()
  .handle(Event.Created) { _, message in
    NSNotificationCenter.defaultCenter().postNotificationName("launchIncomingChat", object: nil)
    NSNotificationCenter.defaultCenter().postNotificationName("reloadMessages", object: nil)
  }
```

**Comment by otymartin** [comment]
@nlutsenko beautiful thank you :+1:
