### ISSUE TITLE
What's the "right" way of using liveQuery in ObjC project?

### ISSUE THREAD

**Issue by hansimmmi** [parse-community/ParseLiveQuery-iOS-OSX#62]
Hi, I've been having somewhat unique issue, since I can't find the answer here, so I think it's unique. 
My project written in ObjC and using cocoa pods. 
So.. like usual, I added liveQuery to Podfile, and pod install, my cocoa pods is 1.0.1.
Also I am using user_frameworks! in pod file, so building the project is fine. 
So.. in objC header file, I user @import ParseLiveQuery; to import the framework, it looks fine, but if I add @import syntax on .m file, I got the error in screen shot. 
Anyway, I imported the framework on header file and try to access the methods, but I can't access any of method of liveQuery. I am not sure I am doing things in right way, or I did forget something important here.  I am kind of new to "mix and match" things, so your advice on me would be very helpful!

![screen shot 2016-09-05 at 4 39 05 pm](https://cloud.githubusercontent.com/assets/7344606/18258265/45dedf64-7387-11e6-9176-4cd97adb71cd.png)

**Comment by rjpalermo1** [comment]
Any luck here hansimmmi?  Have same problem.  Sad the lack of docs for ObjC - all the hipsters moved on to swift I guess...

**Comment by Neilfau** [comment]
Anyone know of any decent ObjC docs / guides?

**Comment by ljs19923** [comment]
Do you find a solution ?
