### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by andrewjedi** [parse-community/ParseLiveQuery-iOS-OSX#63]
Is anyone working on making this compatible with swift 3? Thanks!

**Comment by b992** [comment]
+1

**Comment by vyachesIavskiy** [comment]
It's iOS 10 and Xcode 8 out there already! Maybe update is about to go?

**Comment by agordeev** [comment]
One of Parse members said that this repo is not being actively maintained.

**Comment by mkaya93** [comment]
hi, @nlutsenko will you update library for swift 3 ?

**Comment by flovilmart** [comment]
Merged to master with Carthage support
