### ISSUE TITLE
Swift 3 Error

### ISSUE THREAD

**Issue by mkaya93** [parse-community/ParseLiveQuery-iOS-OSX#72]
Hello,

I'm getting 40 error on framework when I'm trying to build and run my project. Is Anyone facing an issue like this ? 

![ekran resmi 2016-09-26 16 59 05](https://cloud.githubusercontent.com/assets/6665723/18836949/bd3d1696-840a-11e6-8adb-f1b13393d42f.png)

**Comment by chesterhawkins** [comment]
Same here. I think the pod version, v1.0.1, doesn't support swift 3 but the latest version in git, v1.1.0, does.  I was able to build from git and get my code working but I'd prefer the pod.

**Comment by chesterhawkins** [comment]
#68

**Comment by mkaya93** [comment]
@chesterhawkins how did you build from git ? also I tried to install pod with version number but it didn't worked.

**Comment by flovilmart** [comment]
The pod isn't released yet, however you can use the git: / branch: notation in the Podfile to work around that.

**Comment by chesterhawkins** [comment]
@mkaya93 I downloaded the source and opened the project with Xcode. Build the project and the ParseLiveQuery framework should be built. You can import that framework the same way you'd import any other.
I wasn't aware of the method mentioned above for using the git notation in Podfile. I think I'll switch that instead.
