### ISSUE TITLE
Value of type 'PFQuery<PFObject>' has no member 'subscribe'

### ISSUE THREAD

**Issue by mkaya93** [parse-community/ParseLiveQuery-iOS-OSX#73]
Hello, 

I just updated my project for swift 3 and when I'm trying to subscribe with query its giving me this error.

`Value of type 'PFQuery<PFObject>' has no member 'subscribe'
`
I was using this code in swift 2.
`subscription = query.subscribe()`

**Comment by mkaya93** [comment]
hi @nlutsenko @flovilmart ,

I just have a problem  on swift 3.  How can we will use subscribe on swift 3 ?

**Comment by chesterhawkins** [comment]
I also had the same issue.  I wish I knew which page I found this on but this is how I'm subscribing now (I don't have my code in front of me so it may be a little off):
1. Create a client:  let myClient : Client = ParseLiveQuery.client()
2. Create your query:  let query: PFQuery = PFQuery ...
3. Use client to subscribe to query:  let sub: Subscription = myClient.subscribe(query)
4. Handle events with subscription: sub.handle(EventType) { query, object in
   // Called whenever an object was created
   }

**Comment by flovilmart** [comment]
The subscribe on PFQuery did not work on swift 3 due to updates in the behavior of obj-c generics. I'll try to add it back later

**Comment by mkaya93** [comment]
@flovilmart so how we will use it ?

**Comment by flovilmart** [comment]
As suggested above. Actually, internally, that's how it was done.

**Comment by mkaya93** [comment]
Ok I made it but it didn't work. @flovilmart @chesterhawkins 

```
var sub: Subscription<PFObject>?
        let client: Client = ParseLiveQuery.Client()
        if currentGroup?.parseClassName == "Messages" {
            sub = client.subscribe(messageQuery)
            //subscription = messageQuery.subscribe()

        }else {
            let client = ParseLiveQuery.Client()
            sub = client.subscribe(groupQuery)
            //subscription = groupQuery.subscribe()
        }

        sub?.handle(Event.updated, { (query, T) in
print(T)
})
```

**Comment by mkaya93** [comment]
@flovilmart I also checked and look examples. I mad it like that but I can't get any event with livequery.

**Comment by flovilmart** [comment]
If you don't retain your subscriber/client It will probably be flushed after your method ends

**Comment by mkaya93** [comment]
@flovilmart thank you for your helps its worked.

**Comment by tabvn** [comment]
subscribed. XCode 8 and swift 3.x does not work with Live query.

**Comment by flovilmart** [comment]
@tabvn what do you mean?

**Comment by tabvn** [comment]
@flovilmart i mean this Parse Live Query does not work in swift 3 

i have test live query use Javascript client it work fine. 

however in IOS swift 3.x it does not recieve any subscription 

i have:   Gang.registerSubclass()
before
Parse.initialize(with: configuration)

<code>
        let liveQueryClient = ParseLiveQuery.Client()

```
    let subscription: Subscription<Gang>?


    let gangQuery: PFQuery<Gang>  = Gang.query()!.whereKey("userId", equalTo: userId) as! PFQuery<Gang>


    subscription = liveQueryClient.subscribe(gangQuery).handle(Event.updated) { _, gang in

        print("gang updated")
    }
    </code>
```

and this is gang class

<code>

import Parse

class Gang: PFObject, PFSubclassing {

   class func parseClassName() -> String {
        return "Gang"
    }

}
</code>

**Comment by flovilmart** [comment]
If you don't store the subscription somewhere, it's not gonna be retained...

**Comment by tabvn** [comment]
I was fan of Firebase however i 'm so exciting moving to Parse server self hosting. 

in IOS mostly work fine however live query does not work. I hope for Arduino Parse is works well too.

**Comment by tabvn** [comment]
@flovilmart Could you please give me a little more direction ? Thank you

**Comment by flovilmart** [comment]
`let subscription: Subscription<Gang>?`

Should be a class property otherwise, if it's just a local variable, the ARC will release it and your subscription object will be released:

ex:

```

class MyClass {
  // property
  var suscription: Subscription<Gang>?
  func register() {
     let gangQuery: PFQuery<Gang>  = Gang.query()!.whereKey("userId", equalTo: userId) as! PFQuery<Gang>
    // set the subscription as the property to retain it
    subscription = liveQueryClient.subscribe(gangQuery, subclassType: Gang.self).handle(Event.updated) { _, gang in
        print("gang updated")
    }
  }
}
```

**Comment by tabvn** [comment]
@flovilmart  i tried and it does not work too. (i posted wrong message)

**Comment by tabvn** [comment]
@flovilmart i made video screenshot it work perfect for Javascript Client. Unfortunately it does not work on Swift 3.x 

https://www.youtube.com/watch?v=BnuuYe6i7OQ&feature=youtu.be

**Comment by flovilmart** [comment]
I can say that this should correctly work, as I'm currently preparing a talk about it, and have if fully working. Is the subscription event fired correctly?

**Comment by tabvn** [comment]
@flovilmart it does not work (i was sent wrong message "it does work ")

**Comment by flovilmart** [comment]
@tabvn I'm really not sure why it doesn't work on your setup, check that here: https://github.com/flovilmart/cocoaheads-mtl-parse-server/blob/master/ios/CocoaHeaders/LiveTableViewController.swift

it's working correctly...

**Comment by tabvn** [comment]
Regarding this issue.  i replaced
let liveQueryClient = ParseLiveQuery.Client()
by 

let liveQueryClient = ParseLiveQuery.Client.shared! 

and it works fine now.

i think someone need update the code in this sample as well ?
https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX/blob/master/Examples/LiveQueryDemo/main.swift

**Comment by tabvn** [comment]
@flovilmart Thank you alot for your all the helps/

**Comment by flovilmart** [comment]
Using directly the Client should work correctly, under the hood, the shared client creates a client

**Comment by tabvn** [comment]
Thank you one again @flovilmart , i can confirm that this library work well in swift 3.x 
here is my video screenshot after spent a day for Live query :) 

https://www.youtube.com/watch?v=40dufBEGU_o
