### ISSUE TITLE
Publish v1.1.0

### ISSUE THREAD

**Issue by devladinci** [parse-community/ParseLiveQuery-iOS-OSX#75]
Current version of the pod in [Cocoapods](https://cocoapods.org/pods/ParseLiveQuery) is 1.0.1.

Probably last version is only verified with `lint`, can you please `pod trunk push` the latest version.

**Comment by Rovalx** [comment]
For now just add 
`pod 'ParseLiveQuery', :git=> 'https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX.git'`
Works for me

**Comment by flovilmart** [comment]
it's just been released! https://cocoapods.org/pods/ParseLiveQuery
