### ISSUE TITLE
No Event Handled

### ISSUE THREAD

**Issue by danielchangsoojones** [parse-community/ParseLiveQuery-iOS-OSX#79]
Somewhere in the documentation, it should say that you need to make sure that the subscription variable is placed outside the function you are using it in. If it is left inside, then when the function finishes, it deallocates the subscription, so it will never get called. Took me a while to find why I wasn't receiving any event callback at all.

**Comment by flovilmart** [comment]
It come with ARC and the memory management model in Swift. Yes we could put something in the docs that say: Hey! Make sure your subscription is retained otherwise it will be disposed.

**Comment by alecsechechel** [comment]
Please add this in docs "Hey! Make sure your subscription is retained otherwise it will be disposed.".
It will save a lot time of developers!

**Comment by flovilmart** [comment]
You can make the PR if you like.
