### ISSUE TITLE
README is outdated?

### ISSUE THREAD

**Issue by dielsonsales** [parse-community/ParseLiveQuery-iOS-OSX#80]
It seems that in Swift 3, query doesn't have a `subscribe` method anymore, which makes the README outdated. I guess it should have a section `getting started` with a more complete usage description, common errors etc...

**Comment by flovilmart** [comment]
You are right, due to changes in the handling of lightweight genetics in objective C, the subscribe method is not available anymore with Swift 3. 

Do you want to propose à PR with the updated README?

**Comment by dielsonsales** [comment]
I can do that later in this week. It seem though that pull requests are only accepted by developers who have signed the NDA, right?

**Comment by flovilmart** [comment]
This is not an NDA but CLA, see more info here: https://code.facebook.com/cla
