### ISSUE TITLE
I'm using in tableview with swift3. Could you anyone some helps me?

### ISSUE THREAD

**Issue by ShawnBaek** [parse-community/ParseLiveQuery-iOS-OSX#85]
Hi I'm trying to use live query.

My question is really simple. Could you please let me know how do I use that?

My original code is here

in Tableviewcontroller

loadPost(){
       blah blah~~~

       //Get All of Post
        let postQuery = PFQuery.orQuery(withSubqueries: [friendsPostQuery, myPostQuery, sellPostQuery])
        postQuery.includeKeys(["postBy", "comment", "comment.commentBy"])
        postQuery.limit = self.page
        postQuery.addDescendingOrder("createdAt")
        
        postQuery.findObjectsInBackground { (objects:[PFObject]?, error:Error?) in blah blah~~~

}

I want subscribe of postQuery.

So I changed my code like this

Step 1. Make "Post" Class 
class Post: PFObject, PFSubclassing 

Step 2. declare subscription variable in tableviewcontroller and postQuery variable.

   var postQuery: PFQuery<PFObject>? {
        
        return Post.query()?
            .whereKey("hi", equalTo: "Something")
        <-- How do I set like loadPost()?
    }
    
    //Post Subscription
    private var subscription: Subscription<Post>?

Could you please let me know some guide?

And Can I use live query with swift3?

**Comment by flovilmart** [comment]
Hi, there is an example here for a generic LiveTableViewController: https://github.com/flovilmart/cocoaheads-mtl-parse-server/blob/master/ios/CocoaHeaders/LiveTableViewController.swift

**Comment by yoshiboarder** [comment]
@flovilmart Thank you so much. It helps me a lot :)

**Comment by ShawnBaek** [comment]
@flovilmart 

Thanks for sharing your code.

I'm trying to use your code but I got an errors.

when Init() -> FatalError()

[My snippet code](https://gist.github.com/yoshiboarder/c4dd5d5c27cdd849e7f7482c66734b87)

Could you please advising me?

**Comment by flovilmart** [comment]
What's the fatalError?

**Comment by ShawnBaek** [comment]
I found it. It just happened I didn't set initialize TableViewController. My mistake..

But I'm struggling to implementation. Could you advising me?

My app has consist of 5 tabs and 5 viewController(Table, Collection, View, etc..). 

I want implement livequery in my first tab as TableViewController.

Then where I put this code? in NavigationController? or TabController?

```
  // Create the liveQueryClient
    client = ParseLiveQuery.Client.shared

    let query = Post.query() as! PFQuery<Post>
    query.whereKeyExists("objectId")

    let liveQueryController = FeedVC(query: query, client: client)

    viewControllers = [liveQueryController]
```

And Is there a way to use without required init() in FeedVC?

Here is what I'm trying to do it. And fetchObjects() is not called.
https://gist.github.com/yoshiboarder/0c4060d483f0b04e3195a5e3ed19d7ed

Thanks

**Comment by flovilmart** [comment]
For implementation details, you should probably as over stackoverflow
