### ISSUE TITLE
Error with Carthage

### ISSUE THREAD

**Issue by Droppix** [parse-community/ParseLiveQuery-iOS-OSX#88]
Hi,

I try use ParseLiveQuery with Carthage (XCode 8 with Objective-C), but I have this problem :
(I added Parse, ParseLiveQuery, BoltsSwift, Bolts and SocketRocket frameworks in embedded Binairies)

"dyld: Library not loaded: @rpath/BoltsSwift.framework/BoltsSwift
  Referenced from: /Users/xxxxx/Library/Developer/CoreSimulator/Devices/DEE3A235-EC7B-4C7F-9475-27A7404608C8/data/Containers/Bundle/Application/0C13B0E5-B5D1-400C-8DAA-90C60420BCB4/XXX.app/Frameworks/ParseLiveQuery.framework/ParseLiveQuery
  Reason: Incompatible library version: ParseLiveQuery requires version 1.0.0 or later, but BoltsSwift provides version 0.0.0"

Any suggestions ?

Thanks

**Comment by dstarke** [comment]
This seems like the same issue as #84
