### ISSUE TITLE
App Crashes on try JSONSerialization.data

### ISSUE THREAD

**Issue by willsmillie** [parse-community/ParseLiveQuery-iOS-OSX#89]
I'm running into an issue when attempting to call addCreateHandler:. After searching around online it appears it may have something to do with Swift 3, though I'm still using Objective-C in my project.

This is the error I get:

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (PFObject)'

The error occurs on line 208 in ClientPrivate.swift

**Comment by danielmhanover** [comment]
+1

**Comment by Vortec4800** [comment]
I started getting this crash as well. I'll look into it, but has anyone else found a solution or know the root cause?

**Comment by themoonlitknight** [comment]
It happens to me too, after subscribed to events

**Comment by denistrofimov** [comment]
QueryEncoder.swift:39
```
 } else if let objects = val as? [PFObject] {
   let result = objects.map({ (object) -> Value in
        return PFPointerObjectEncoder.object().encode(object) as! Value
   })
   encodedQueryDictionary[key] = result as? Value
```

encodedQueryDictionary getter should check arrays to (for $in for example)
