### ISSUE TITLE
Class names should be prefixed

### ISSUE THREAD

**Issue by JoeSzymanski** [parse-community/ParseLiveQuery-iOS-OSX#90]
The use of very generic class names has caused us some problems. Having a class named Client or Subscribe is likely to conflict with class names elsewhere, possibly even with Apple class names.

Apple documentation strongly suggests using 3-character prefixes on all classnames to avoid this name spacing problem. All of the classes in here should be updated to have a prefix (maybe PLQ).

**Comment by flovilmart** [comment]
Which was recommended with Objective-C but not anymore with Swift.
You don,t need to do it as all classes are module prefixed. 

If you have any potential conflict with your code:

```
import ParseLiveQuery

struct Client { // That can't be good

}

let client = Client() // Your client
let PLQC = ParseLiveQuery.Client // the PLCLient
```

you can also define your own type aliases, that are gonna be available to your own module (app)

``` 
PLQ.swift
import ParseLiveQuery
typealias PLQClient = ParseLiveQuery.Client

```

This way you don't even need to `import ParseLiveQuery`  anywhere else in your code.

Let me know if that work for you.

**Comment by JoeSzymanski** [comment]
I think I see what's happening. I was not fully aware of the name spacing for Swift modules. I'll close this issue.
