### ISSUE TITLE
ParseLiveQuery with matchesQuery Crash

### ISSUE THREAD

**Issue by ljs19923** [parse-community/ParseLiveQuery-iOS-OSX#97]
Hi ! Im trying to use ParseLiveQuery with matchesQuery: but that doesn't works.... Anybody knows why ? 

```
self.query1 = [PFQuery queryWithClassName:kGroupUserClasseName];
[self.query1 whereKey:"user.objectId" equalTo:[PFUser currentUser].objectId];
    
    
    self.query2 = [PFQuery queryWithClassName:kGroupClasseName];
   [self.query2 whereKey:@"users" matchesQuery:self.query1];
```

Thanks you !

![image](https://cloud.githubusercontent.com/assets/5727223/22355683/0539eb58-e424-11e6-9055-8146393b2725.png)

**Comment by dstarke** [comment]
I'm pretty sure that the LiveQuery server doesn't currently support `matchesQuery` constraints or relation queries, but it shouldn't crash.

**Comment by flovilmart** [comment]
What's the crash?

**Comment by flovilmart** [comment]
Alright so query serialization should also be the one from the iOS SDK, we should expose those once and for all (JSON encoders/decoders for objects/queries etc...). Would you take care of it @dstarke ?
