### ISSUE TITLE
Invalid State: Cannot call send: until connection is open  -- > Solution

### ISSUE THREAD

**Issue by ljs19923** [parse-community/ParseLiveQuery-iOS-OSX#98]
I added this condition in ClientPrivate.swift so that no SRWebSocket error occurred if the connection is not yet open when I try to unsubscribe.

What do you think ? Before that I had a crash if I tried to unsubscribe after subscribe and a slow connection.

What do you think about that ?

That's works for me

![image](https://cloud.githubusercontent.com/assets/5727223/22740320/41141c76-eddd-11e6-8ad5-851600d9709e.png)

**Comment by eeallen1** [comment]
@JulienLevallois This seems to have fixed the problem for me too. I'll let you know if I notice any downsides

**Comment by flovilmart** [comment]
@JulienLevallois #81 introduces the `client.update(subscription, toQuery: newQuery)` 

If your parse-server is up to date that should work as-is. We're finalizing our tests at the moment with that feature.
