### ISSUE TITLE
Nil value in subscription record's handler

### ISSUE THREAD

**Issue by nzatsepilov** [parse-community/ParseLiveQuery-iOS-OSX#99]
Is it sdk's issue, or just trick? I have to put subscription to strong property to have callback here. Else I had nil handler for all events (SubscriptionRecord.swift)
`liveQueryClient.subscribe(query).handle(Event.created, { (_, object) in
            ...
        })`
With strong property callback works
I'm using swift 3

**Comment by flovilmart** [comment]
Yes you need to retain you subscription as long as you need it, the SDK doesn't retain it for you.

**Comment by nzatsepilov** [comment]
@flovilmart Thanks
